import express from 'express';
import bcrypt from 'bcryptjs';
import {z} from 'zod';
import {createApp,query,tx,asyncHandler,auth,allow,ApiError,listen,upload} from '@uddeepto/common';
const app=createApp('frontend-api');
app.use(auth());
// Look up current roles and account state; never authorize from a stale role claim.
app.use(asyncHandler(async(req,_res,next)=>{const u=(await query('SELECT id,role,account_status FROM users WHERE id=$1',[req.user.sub])).rows[0];if(!u||u.account_status!=='active')throw new ApiError(401,'Account is not active');req.user.role=u.role;next();}));
const run=fn=>asyncHandler(async(req,res)=>{const value=await fn(req,res);if(!res.headersSent)res.json(value??{ok:true});});
const uuid=v=>z.string().uuid().parse(v);
const text=v=>z.string().trim().min(1).max(10000).parse(v);
const paging=req=>[Math.min(100,Math.max(1,parseInt(req.query.limit)||20)),Math.max(0,parseInt(req.query.offset)||0)];
const admin=req=>{if(req.user.role!=='admin')throw new ApiError(403,'Admin required');};
const learner=req=>{if(req.user.role==='hirer')throw new ApiError(403,'Learner permission required');};
const one=async(sql,args)=>{const r=await query(sql,args);if(!r.rowCount)throw new ApiError(404,'Not found');return r.rows[0];};
const ownJob=async req=>{const j=await one('SELECT creator_id FROM jobs WHERE id=$1',[uuid(req.params.id)]);if(j.creator_id!==req.user.sub&&req.user.role!=='admin')throw new ApiError(403,'Only the job owner can view applications');};
async function communityAccess(req){const c=await one(`SELECT c.*,m.status membership,m.is_moderator FROM communities c LEFT JOIN community_members m ON m.community_id=c.id AND m.member_id=$2 WHERE c.id=$1`,[uuid(req.params.id),req.user.sub]);c.can_manage=c.creator_id===req.user.sub||req.user.role==='admin'||(c.membership==='approved'&&c.is_moderator);if(c.creator_id===req.user.sub||req.user.role==='admin')c.membership='approved';return c;}
async function requireMember(req){const c=await communityAccess(req);if(c.membership!=='approved')throw new ApiError(403,'Approved membership required');return c;}
async function conversationAccess(req){await one('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[uuid(req.params.id),req.user.sub]);}
app.get('/dashboard',run(async req=>{
  const id=req.user.sub;
  if(req.user.role==='hirer')return {...(await one(`SELECT (SELECT count(*) FROM jobs WHERE creator_id=$1) jobs,(SELECT count(*) FROM jobs WHERE creator_id=$1 AND status='open') open_jobs,(SELECT count(*) FROM job_applications a JOIN jobs j ON j.id=a.job_id WHERE j.creator_id=$1) applications,(SELECT count(*) FROM showcase_posts WHERE creator_id=$1 AND deleted_at IS NULL) posts`,[id])),recent:(await query('SELECT j.title,a.status FROM job_applications a JOIN jobs j ON j.id=a.job_id WHERE j.creator_id=$1 ORDER BY a.applied_at DESC LIMIT 5',[id])).rows};
  return {...(await one(`SELECT (SELECT count(*) FROM course_enrollments WHERE user_id=$1 AND status IN ('active','completed')) enrollments,(SELECT count(*) FROM contest_participants WHERE participant_id=$1) contests,(SELECT count(*) FROM community_members WHERE member_id=$1 AND status='approved') communities,(SELECT count(*) FROM job_applications WHERE applicant_id=$1) applications`,[id])),recent:(await query(`SELECT c.title,e.status FROM course_enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1 AND e.status IN('active','completed') ORDER BY e.enrolled_at DESC LIMIT 5`,[id])).rows,upcoming:(await query(`SELECT id,name,status,starting_time FROM webinars WHERE status='scheduled' AND starting_time>now() ORDER BY starting_time LIMIT 3`)).rows};
}));
app.get('/people',run(async req=>(await query(`SELECT id,name,username,role FROM users WHERE account_status='active' AND (name ILIKE $1 OR username::text ILIKE $1) ORDER BY name LIMIT 30`,[`%${String(req.query.q||'').slice(0,100)}%`])).rows));
app.get('/profile/:id',run(async req=>{const p=await one(`SELECT id,name,username,bio,role,created_at,(picture IS NOT NULL) has_picture,(cover_image IS NOT NULL) has_cover_image FROM users WHERE id=$1 AND account_status='active'`,[uuid(req.params.id)]);p.interests=(await query('SELECT i.id,i.name FROM user_interests ui JOIN interest_categories i ON i.id=ui.interest_id WHERE ui.user_id=$1',[p.id])).rows;p.posts=(await query(`SELECT id,content FROM showcase_posts WHERE creator_id=$1 AND deleted_at IS NULL AND visibility='public' ORDER BY created_at DESC LIMIT 12`,[p.id])).rows;return p;}));
app.get('/profile/:id/picture',run(async(req,res)=>{const p=await one(`SELECT picture,picture_mime_type FROM users WHERE id=$1 AND account_status='active'`,[uuid(req.params.id)]);if(!p.picture)throw new ApiError(404,'Profile picture not found');res.set('Cache-Control','private, max-age=300').type(p.picture_mime_type).send(p.picture);}));
app.get('/profile/:id/cover',run(async(req,res)=>{const p=await one(`SELECT cover_image,cover_image_mime_type FROM users WHERE id=$1 AND account_status='active'`,[uuid(req.params.id)]);if(!p.cover_image)throw new ApiError(404,'Profile cover not found');res.set('Cache-Control','private, max-age=300').type(p.cover_image_mime_type).send(p.cover_image);}));
app.patch('/profile',upload.fields([{name:'picture',maxCount:1},{name:'cover_image',maxCount:1}]),run(async req=>{let interestIds=req.body.interest_ids;try{if(typeof interestIds==='string')interestIds=JSON.parse(interestIds);}catch{throw new ApiError(422,'Invalid interest selection');}const b=z.object({name:z.string().trim().min(2).max(150),username:z.string().regex(/^[A-Za-z0-9_.-]{3,40}$/),bio:z.string().max(3000),interest_ids:z.array(z.string().uuid()).max(30),remove_picture:z.enum(['true','false']).optional(),remove_cover_image:z.enum(['true','false']).optional()}).parse({...req.body,interest_ids:interestIds});const picture=req.files?.picture?.[0],cover=req.files?.cover_image?.[0];for(const file of [picture,cover])if(file&&!instructorImageTypes.has(file.mimetype))throw new ApiError(422,'Use a JPEG, PNG, WebP, or AVIF image');await tx(async db=>{const values=[b.name,b.username,b.bio];const fields=['name=$1','username=$2','bio=$3'];const add=(column,value)=>{values.push(value);fields.push(`${column}=$${values.length}`);};if(picture){add('picture',picture.buffer);add('picture_mime_type',picture.mimetype);}else if(b.remove_picture==='true'){add('picture',null);add('picture_mime_type',null);}if(cover){add('cover_image',cover.buffer);add('cover_image_mime_type',cover.mimetype);}else if(b.remove_cover_image==='true'){add('cover_image',null);add('cover_image_mime_type',null);}values.push(req.user.sub);await db.query(`UPDATE users SET ${fields.join(',')} WHERE id=$${values.length}`,values);await db.query('DELETE FROM user_interests WHERE user_id=$1',[req.user.sub]);for(const id of new Set(b.interest_ids))await db.query('INSERT INTO user_interests(user_id,interest_id) VALUES($1,$2)',[req.user.sub,id]);});}));
const showcaseProjection=`p.id,p.creator_id,p.content,p.created_at,u.name creator_name,i.name category_name,(SELECT count(*) FROM showcase_post_reactions WHERE post_id=p.id) reactions,(SELECT count(*) FROM showcase_post_comments WHERE post_id=p.id AND deleted_at IS NULL) comments,EXISTS(SELECT 1 FROM showcase_post_reactions WHERE post_id=p.id AND user_id=$1 AND reaction='love') my_reaction,COALESCE((SELECT json_agg(json_build_object('id',m.id,'mime_type',m.mime_type,'file_name',m.file_name) ORDER BY m.sort_order) FROM showcase_post_media m WHERE m.post_id=p.id),'[]'::json) media`;
const showcaseFrom='FROM showcase_posts p JOIN users u ON u.id=p.creator_id JOIN interest_categories i ON i.id=p.category_id';
app.get('/showcase',run(async req=>{const[limit,offset]=paging(req);return(await query(`SELECT ${showcaseProjection} ${showcaseFrom} WHERE p.deleted_at IS NULL AND p.visibility='public' AND p.content ILIKE $2 AND($3::uuid IS NULL OR p.category_id=$3) ORDER BY p.created_at DESC LIMIT $4 OFFSET $5`,[req.user.sub,`%${String(req.query.q||'').slice(0,200)}%`,req.query.category?uuid(req.query.category):null,limit,offset])).rows;}));
app.get('/showcase/:id',run(async req=>one(`SELECT ${showcaseProjection} ${showcaseFrom} WHERE p.id=$2 AND p.deleted_at IS NULL AND p.visibility='public'`,[req.user.sub,uuid(req.params.id)])));
app.get('/showcase/:id/media/:mediaId',auth(false),run(async(req,res)=>{const media=await one('SELECT mime_type,media_blob,file_name FROM showcase_post_media m JOIN showcase_posts p ON p.id=m.post_id WHERE m.id=$1 AND m.post_id=$2 AND p.deleted_at IS NULL AND p.visibility=\'public\'',[uuid(req.params.mediaId),uuid(req.params.id)]);if(!media)throw new ApiError(404,'Media not found');res.type(media.mime_type).set('Content-Disposition',`inline; filename="${String(media.file_name||'media').replace(/"/g,'')}"`).send(media.media_blob);}));
app.get('/instructors/:id/image',run(async(req,res)=>{const instructor=await one('SELECT image_blob,image_mime_type FROM instructors WHERE id=$1',[uuid(req.params.id)]);if(!instructor.image_blob)throw new ApiError(404,'Instructor image not found');res.set('Cache-Control','private, max-age=300').type(instructor.image_mime_type).send(instructor.image_blob);}));
app.get('/course-covers/:id',run(async(req,res)=>{const course=await one(`SELECT cover_image,cover_image_mime_type FROM courses WHERE id=$1 AND(status='published' OR creator_id=$2 OR $3='admin')`,[uuid(req.params.id),req.user.sub,req.user.role]);if(!course.cover_image)throw new ApiError(404,'Course cover not found');res.set('Cache-Control','private, max-age=300').type(course.cover_image_mime_type).send(course.cover_image);}));
app.post('/showcase',auth(),upload.array('media',10),run(async req=>{const files=req.files||[];if(files.some(file=>!['image','audio','video'].includes(file.mimetype.split('/')[0])))throw new ApiError(422,'Only image, audio, and video files are allowed');return tx(async db=>{const post=(await db.query('INSERT INTO showcase_posts(creator_id,category_id,content,visibility) VALUES($1,$2,$3,$4) RETURNING *',[req.user.sub,req.body.category_id,text(req.body.content),req.body.visibility||'public'])).rows[0];for(const[file,index]of files.entries())await db.query('INSERT INTO showcase_post_media(post_id,mime_type,media_blob,file_name,sort_order) VALUES($1,$2,$3,$4,$5)',[post.id,file.mimetype,file.buffer,file.originalname,index]);return post;});}));
async function visiblePost(id){return one(`SELECT id FROM showcase_posts WHERE id=$1 AND visibility='public' AND deleted_at IS NULL`,[uuid(id)]);}
app.delete('/showcase/:id',run(async req=>{const r=await query('UPDATE showcase_posts SET deleted_at=now() WHERE id=$1 AND(creator_id=$2 OR $3=\'admin\') RETURNING id',[uuid(req.params.id),req.user.sub,req.user.role]);if(!r.rowCount)throw new ApiError(403,'Not your post');}));
async function toggleReaction(table,field,id,user){await tx(async db=>{await db.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${table}:${id}:${user}`]);const removed=await db.query(`DELETE FROM ${table} WHERE ${field}=$1 AND user_id=$2 AND reaction='love'`,[id,user]);if(!removed.rowCount)await db.query(`INSERT INTO ${table}(${field},user_id,reaction) VALUES($1,$2,'love')`,[id,user]);});}
app.put('/showcase/:id/reaction',run(async req=>{await visiblePost(req.params.id);await toggleReaction('showcase_post_reactions','post_id',req.params.id,req.user.sub);}));
app.get('/showcase/:id/comments',run(async req=>{await visiblePost(req.params.id);return(await query(`SELECT c.id,c.commenter_id,c.content,u.name,(SELECT count(*) FROM showcase_post_comment_reactions WHERE comment_id=c.id) reactions,EXISTS(SELECT 1 FROM showcase_post_comment_reactions WHERE comment_id=c.id AND user_id=$2 AND reaction='love') my_reaction FROM showcase_post_comments c JOIN users u ON u.id=c.commenter_id WHERE c.post_id=$1 AND c.deleted_at IS NULL ORDER BY c.created_at LIMIT 100`,[req.params.id,req.user.sub])).rows;}));
app.post('/showcase/:id/comments',run(async req=>{await visiblePost(req.params.id);return(await query('INSERT INTO showcase_post_comments(post_id,commenter_id,content) VALUES($1,$2,$3) RETURNING id',[req.params.id,req.user.sub,text(req.body.content)])).rows[0];}));
app.put('/comments/:id/reaction',run(async req=>{const c=await one('SELECT post_id FROM showcase_post_comments WHERE id=$1 AND deleted_at IS NULL',[uuid(req.params.id)]);await visiblePost(c.post_id);await toggleReaction('showcase_post_comment_reactions','comment_id',req.params.id,req.user.sub);}));
const catalogs={courses:{title:'title',columns:'price,currency,slug',visible:"status='published'"},contests:{title:'name',columns:'entry_fee,currency,starting_time,ending_time',visible:"status IN ('published','completed','cancelled')"},webinars:{title:'name',columns:'starting_time,ending_time',visible:"status IN ('scheduled','live','completed','cancelled')"},communities:{title:'name',columns:'slug,is_private',visible:'true'}};
app.get('/catalog/:kind',run(async req=>{learner(req);const{kind}=req.params;const cfg=catalogs[kind];if(!cfg)throw new ApiError(404,'Unknown catalog');const[limit,offset]=paging(req);const args=[req.user.sub,`%${String(req.query.q||'').slice(0,200)}%`,req.query.category?uuid(req.query.category):null,limit,offset];let filter=`t.${cfg.visible}`;if(kind==='communities')filter='true';if(req.query.tab==='enrolled'&&kind==='courses')filter+=` AND EXISTS(SELECT 1 FROM course_enrollments WHERE course_id=t.id AND user_id=$1 AND status IN('active','completed'))`;if(['webinars','contests'].includes(kind)){const tab=req.query.tab;if(tab==='ongoing')filter+=` AND starting_time<=now() AND ending_time>=now() AND t.status NOT IN('completed','cancelled')`;if(tab==='upcoming')filter+=` AND starting_time>now() AND t.status NOT IN('completed','cancelled')`;if(tab==='previous')filter+=` AND(ending_time<now() OR t.status IN('completed','cancelled'))`;}
 const extras=kind==='courses'?`,EXISTS(SELECT 1 FROM course_enrollments WHERE course_id=t.id AND user_id=$1 AND status IN('active','completed')) enrolled`:kind==='communities'?`,(SELECT count(*) FROM community_members WHERE community_id=t.id AND status='approved') member_count,($1::uuid IS NOT NULL) authenticated`:',($1::uuid IS NOT NULL) authenticated';
 const instructorFields=kind==='courses'?',t.instructor_id,ins.name instructor_name,ins.designation instructor_designation,ins.details instructor_details,ins.image_mime_type instructor_image_mime_type,(ins.image_blob IS NOT NULL) instructor_has_image':'';
 const courseCoverFields=kind==='courses'?',t.cover_image_mime_type,(t.cover_image IS NOT NULL) has_cover_image':'';
 const instructorJoin=kind==='courses'?' LEFT JOIN instructors ins ON ins.id=t.instructor_id':'';
 return(await query(`SELECT t.id,t.${cfg.title},t.description,${kind==='communities'?"'active' AS status":'t.status'},${cfg.columns.split(',').map(c=>'t.'+c).join(',')},u.name creator_name,i.name category_name ${instructorFields} ${courseCoverFields} ${extras} FROM ${kind} t JOIN users u ON u.id=t.creator_id JOIN interest_categories i ON i.id=t.category_id${instructorJoin} WHERE ${filter} AND(t.${cfg.title} ILIKE $2 OR t.description ILIKE $2) AND($3::uuid IS NULL OR t.category_id=$3) ORDER BY t.created_at DESC LIMIT $4 OFFSET $5`,args)).rows;
}));
app.get('/detail/:kind/:id',run(async req=>{learner(req);const{kind}=req.params;uuid(req.params.id);if(!['courses','contests','webinars'].includes(kind))throw new ApiError(404,'Unknown kind');const cfg=catalogs[kind];const t=await one(`SELECT id,creator_id FROM ${kind} WHERE id=$1 AND(${cfg.visible} OR creator_id=$2 OR $3='admin')`,[req.params.id,req.user.sub,req.user.role]);if(kind==='courses'){const enrollment=await query(`SELECT status FROM course_enrollments WHERE course_id=$1 AND user_id=$2 AND status IN('active','completed')`,[t.id,req.user.sub]);return{enrolled:!!enrollment.rowCount,materials:(await query(`SELECT m.id,m.name,m.is_preview,m.content_blob IS NOT NULL has_blob,EXISTS(SELECT 1 FROM completed_course_materials WHERE material_id=m.id AND user_id=$2) completed FROM course_materials m WHERE course_id=$1 ORDER BY sort_order`,[t.id,req.user.sub])).rows};}const participants=await query(`SELECT 1 FROM ${kind==='contests'?'contest':'webinar'}_participants WHERE ${kind==='contests'?'contest':'webinar'}_id=$1 AND participant_id=$2 ${kind==='webinars'?"AND status IN('registered','attended')":"AND payment_status='paid'"}`,[t.id,req.user.sub]);if(kind==='webinars')return{joined:!!participants.rowCount,meeting_url:participants.rowCount?(await one('SELECT meeting_url FROM webinars WHERE id=$1',[t.id])).meeting_url:null};const started=await query('SELECT 1 FROM contests WHERE id=$1 AND starting_time<=now()',[t.id]);return{joined:!!participants.rowCount,problems:started.rowCount?(await query('SELECT id,name,description,points,sample_input,sample_output FROM contest_problems WHERE contest_id=$1 ORDER BY sort_order',[t.id])).rows:[],leaderboard:(await query('SELECT u.id,u.name,p.points FROM contest_participants p JOIN users u ON u.id=p.participant_id WHERE contest_id=$1 ORDER BY points DESC,participated_at LIMIT 50',[t.id])).rows};}));
app.put('/courses/:id/complete/:materialId',run(async req=>{learner(req);await tx(async db=>{const e=await db.query(`SELECT 1 FROM course_enrollments WHERE course_id=$1 AND user_id=$2 AND status IN('active','completed') FOR UPDATE`,[uuid(req.params.id),req.user.sub]);if(!e.rowCount)throw new ApiError(403,'Enrollment required');await db.query('INSERT INTO completed_course_materials(course_id,user_id,material_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[req.params.id,req.user.sub,uuid(req.params.materialId)]);await db.query(`UPDATE course_enrollments SET status='completed',completed_at=now() WHERE course_id=$1 AND user_id=$2 AND NOT EXISTS(SELECT 1 FROM course_materials m WHERE course_id=$1 AND NOT EXISTS(SELECT 1 FROM completed_course_materials WHERE material_id=m.id AND user_id=$2))`,[req.params.id,req.user.sub]);});}));
app.post('/webinars/:id/join',run(async req=>{learner(req);await tx(async db=>{const w=(await db.query('SELECT * FROM webinars WHERE id=$1 FOR UPDATE',[uuid(req.params.id)])).rows[0];if(!w||!['scheduled','live'].includes(w.status)||new Date(w.ending_time)<new Date())throw new ApiError(409,'Registration closed');const existing=await db.query(`SELECT 1 FROM webinar_participants WHERE webinar_id=$1 AND participant_id=$2 AND status IN('registered','attended')`,[w.id,req.user.sub]);if(existing.rowCount)return;const count=Number((await db.query(`SELECT count(*) FROM webinar_participants WHERE webinar_id=$1 AND status IN('registered','attended')`,[w.id])).rows[0].count);if(w.capacity&&count>=w.capacity)throw new ApiError(409,'Webinar is full');await db.query(`INSERT INTO webinar_participants(webinar_id,participant_id) VALUES($1,$2) ON CONFLICT(webinar_id,participant_id) DO UPDATE SET status='registered'`,[w.id,req.user.sub]);});}));
app.post('/contests/:id/join',run(async req=>{learner(req);await tx(async db=>{const c=(await db.query('SELECT * FROM contests WHERE id=$1 FOR UPDATE',[uuid(req.params.id)])).rows[0];if(!c||c.status!=='published'||new Date(c.ending_time)<new Date())throw new ApiError(409,'Contest unavailable');if(Number(c.entry_fee)>0)throw new ApiError(402,'Paid entries need a payment provider; contact the organizer.');if((await db.query('SELECT 1 FROM contest_participants WHERE contest_id=$1 AND participant_id=$2',[c.id,req.user.sub])).rowCount)return;const n=Number((await db.query('SELECT count(*) FROM contest_participants WHERE contest_id=$1',[c.id])).rows[0].count);if(c.max_participants&&n>=c.max_participants)throw new ApiError(409,'Contest is full');await db.query(`INSERT INTO contest_participants(contest_id,participant_id,payment_status) VALUES($1,$2,'paid')`,[c.id,req.user.sub]);});}));
app.post('/contests/:id/submit',run(async req=>{learner(req);const c=await one(`SELECT id FROM contests WHERE id=$1 AND status='published' AND starting_time<=now() AND ending_time>=now()`,[uuid(req.params.id)]);await one(`SELECT 1 FROM contest_participants WHERE contest_id=$1 AND participant_id=$2 AND payment_status='paid'`,[c.id,req.user.sub]);return(await query('INSERT INTO contest_submissions(contest_id,participant_id,problem_id,content) VALUES($1,$2,$3,$4) RETURNING id',[c.id,req.user.sub,req.body.problem_id?uuid(req.body.problem_id):null,text(req.body.content)])).rows[0];}));
app.post('/communities',run(async req=>{learner(req);const b=z.object({name:z.string().trim().min(2).max(150),slug:z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/),description:z.string().max(10000),category_id:z.string().uuid(),requires_approval:z.boolean(),is_private:z.boolean()}).parse(req.body);return tx(async db=>{const c=(await db.query('INSERT INTO communities(creator_id,name,slug,description,category_id,requires_approval,is_private) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[req.user.sub,b.name,b.slug,b.description,b.category_id,b.requires_approval,b.is_private])).rows[0];await db.query(`INSERT INTO community_members(community_id,member_id,status,is_moderator,approved_at,approved_by) VALUES($1,$2,'approved',true,now(),$2)`,[c.id,req.user.sub]);await db.query(`INSERT INTO community_chats(community_id,name) VALUES($1,'general')`,[c.id]);return c;});}));
app.get('/communities/:id',run(async req=>{learner(req);const c=await communityAccess(req);return{membership:c.membership,can_manage:c.can_manage,chats:c.membership==='approved'?(await query('SELECT id,name FROM community_chats WHERE community_id=$1 ORDER BY sort_order',[c.id])).rows:[],pending:c.can_manage?(await query(`SELECT m.member_id,u.name FROM community_members m JOIN users u ON u.id=m.member_id WHERE community_id=$1 AND status='pending' LIMIT 100`,[c.id])).rows:[]};}));
app.patch('/communities/:id/members/:userId',run(async req=>{learner(req);const c=await communityAccess(req);if(!c.can_manage)throw new ApiError(403,'Moderator required');const status=z.enum(['approved','rejected','blocked']).parse(req.body.status);await query(`UPDATE community_members SET status=$1,approved_at=CASE WHEN $1='approved' THEN now() ELSE NULL END,approved_by=$2 WHERE community_id=$3 AND member_id=$4`,[status,req.user.sub,c.id,uuid(req.params.userId)]);}));
app.post('/communities/:id/chats',run(async req=>{learner(req);const c=await communityAccess(req);if(!c.can_manage)throw new ApiError(403,'Moderator required');return(await query('INSERT INTO community_chats(community_id,name) VALUES($1,$2) RETURNING id',[c.id,z.string().trim().min(1).max(150).parse(req.body.name)])).rows[0];}));
app.get('/communities/:id/chats/:chatId',run(async req=>{learner(req);await requireMember(req);return(await query(`SELECT * FROM(SELECT m.id,m.content,m.created_at,u.name sender_name FROM community_chat_messages m JOIN users u ON u.id=m.sender_id WHERE community_id=$1 AND chat_id=$2 AND deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 100) recent ORDER BY created_at`,[req.params.id,uuid(req.params.chatId)])).rows;}));
app.post('/communities/:id/chats/:chatId',run(async req=>{learner(req);await requireMember(req);return(await query('INSERT INTO community_chat_messages(community_id,chat_id,sender_id,content) VALUES($1,$2,$3,$4) RETURNING id',[req.params.id,uuid(req.params.chatId),req.user.sub,text(req.body.content)])).rows[0];}));
app.get('/jobs',run(async req=>{const[limit,offset]=paging(req);const tab=req.query.tab;const filter=tab==='mine'?`j.creator_id=$1`:tab==='applied'?`a.applicant_id=$1`:`j.status='open' AND(application_deadline IS NULL OR application_deadline>now())`;return(await query(`SELECT j.id,j.creator_id,j.title,j.description,j.status,j.type,j.salary_min,j.salary_max,j.currency,j.location,j.is_remote,j.application_deadline,u.name creator_name,a.status application_status FROM jobs j JOIN users u ON u.id=j.creator_id LEFT JOIN job_applications a ON a.job_id=j.id AND a.applicant_id=$1 WHERE ${filter} AND(j.title ILIKE $2 OR j.description ILIKE $2) AND($3='' OR j.type::text=$3) ORDER BY j.created_at DESC LIMIT $4 OFFSET $5`,[req.user.sub,`%${String(req.query.q||'').slice(0,200)}%`,req.query.type||'',limit,offset])).rows;}));
app.get('/jobs/:id/applications',run(async req=>{await ownJob(req);return(await query('SELECT a.applicant_id,a.status,a.cover_letter,a.applied_at,a.resume_blob IS NOT NULL has_resume,u.name,u.username FROM job_applications a JOIN users u ON u.id=a.applicant_id WHERE job_id=$1 ORDER BY applied_at DESC LIMIT 100',[req.params.id])).rows;}));
app.get('/jobs/:id/applications/:userId/resume',run(async(req,res)=>{await ownJob(req);const a=await one('SELECT resume_blob,resume_mime_type FROM job_applications WHERE job_id=$1 AND applicant_id=$2',[req.params.id,uuid(req.params.userId)]);if(!a.resume_blob)throw new ApiError(404,'Resume not found');res.set('Content-Disposition','attachment; filename="resume.pdf"').type('application/octet-stream').send(a.resume_blob);}));
app.patch('/jobs/:id/applications/:userId',run(async req=>{await ownJob(req);const status=z.enum(['shortlisted','accepted','rejected','applied']).parse(req.body.status);await query('UPDATE job_applications SET status=$1 WHERE job_id=$2 AND applicant_id=$3',[status,req.params.id,uuid(req.params.userId)]);}));
app.patch('/jobs/:id/status',run(async req=>{await ownJob(req);await query('UPDATE jobs SET status=$1 WHERE id=$2',[z.enum(['open','closed']).parse(req.body.status),req.params.id]);}));
app.get('/messages',run(async req=>{learner(req);return(await query(`SELECT c.id,c.updated_at,u.name,u.id other_user_id,(SELECT content FROM messages WHERE conversation_id=c.id AND deleted_at IS NULL ORDER BY sent_at DESC LIMIT 1) last_message FROM conversations c JOIN conversation_members mine ON mine.conversation_id=c.id AND mine.user_id=$1 JOIN conversation_members other ON other.conversation_id=c.id AND other.user_id<>$1 JOIN users u ON u.id=other.user_id WHERE (SELECT count(*) FROM conversation_members WHERE conversation_id=c.id)=2 ORDER BY c.updated_at DESC LIMIT 100`,[req.user.sub])).rows;}));
app.post('/messages',run(async req=>{learner(req);const other=uuid(req.body.user_id);if(other===req.user.sub)throw new ApiError(422,'Choose another person');await one(`SELECT id FROM users WHERE id=$1 AND account_status='active'`,[other]);return tx(async db=>{await db.query('SELECT pg_advisory_xact_lock(hashtext($1))',[[other,req.user.sub].sort().join(':')]);const found=await db.query(`SELECT a.conversation_id id FROM conversation_members a JOIN conversation_members b ON b.conversation_id=a.conversation_id WHERE a.user_id=$1 AND b.user_id=$2 AND (SELECT count(*) FROM conversation_members WHERE conversation_id=a.conversation_id)=2 LIMIT 1`,[req.user.sub,other]);if(found.rowCount)return found.rows[0];const c=(await db.query('INSERT INTO conversations DEFAULT VALUES RETURNING id')).rows[0];await db.query('INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2),($1,$3)',[c.id,req.user.sub,other]);return c;});}));
app.get('/messages/:id',run(async req=>{learner(req);await conversationAccess(req);await query('UPDATE conversation_members SET last_read_at=now() WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.sub]);return(await query(`SELECT * FROM(SELECT id,sender_id,content,sent_at FROM messages WHERE conversation_id=$1 AND deleted_at IS NULL ORDER BY sent_at DESC LIMIT 100) latest ORDER BY sent_at`,[req.params.id])).rows;}));
app.post('/messages/:id',run(async req=>{learner(req);await conversationAccess(req);return tx(async db=>{const m=(await db.query('INSERT INTO messages(conversation_id,sender_id,content) VALUES($1,$2,$3) RETURNING id',[req.params.id,req.user.sub,text(req.body.content)])).rows[0];await db.query('UPDATE conversations SET updated_at=now() WHERE id=$1',[req.params.id]);return m;});}));
const managed={
  users:{table:'users',fields:['name','email','username','role','account_status'],select:'u.id,u.name,u.email,u.username,u.role::text role,u.account_status::text account_status,u.created_at,u.last_login_at',from:'users u',search:['u.name','u.email','u.username'],statusField:'u.account_status',statusValues:['active','suspended','deactivated'],sortable:{created_at:'u.created_at',name:'u.name',email:'u.email',role:'u.role',account_status:'u.account_status'},defaultSort:'u.created_at'},
  interest_categories:{table:'interest_categories',fields:['name','slug','icon','description','is_active'],select:'id,name,slug,icon,description,is_active,created_at',search:['name','slug','description'],statusField:'is_active',statusValues:['true','false'],sortable:{created_at:'created_at',name:'name',slug:'slug'},defaultSort:'created_at'},
  courses:{table:'courses',fields:['title','slug','description','category_id','instructor_id','price','currency','status'],owner:true,select:'c.id,c.creator_id,c.instructor_id,c.title,c.slug,c.description,c.category_id,i.name category_name,u.name creator_name,ins.name instructor_name,ins.image_mime_type instructor_image_mime_type,(ins.image_blob IS NOT NULL) instructor_has_image,c.cover_image_mime_type,(c.cover_image IS NOT NULL) has_cover_image,c.price,c.currency,c.status::text status,c.published_at,c.created_at,(SELECT count(*) FROM course_enrollments e WHERE e.course_id=c.id) enrollment_count',from:'courses c JOIN users u ON u.id=c.creator_id JOIN interest_categories i ON i.id=c.category_id LEFT JOIN instructors ins ON ins.id=c.instructor_id',search:['c.title','c.slug','u.name','i.name','ins.name','c.description'],statusField:'c.status',statusValues:['draft','published','archived'],sortable:{created_at:'c.created_at',title:'c.title',status:'c.status',price:'c.price'},defaultSort:'c.created_at'},
  instructors:{table:'instructors',fields:['name','designation','details','social_links'],select:"id,name,designation,details,social_links,image_mime_type,(image_blob IS NOT NULL) has_image,created_at,(SELECT count(*) FROM courses c WHERE c.instructor_id=instructors.id) course_count",from:'instructors',search:['name','designation','details'],sortable:{created_at:'created_at',name:'name',designation:'designation'},defaultSort:'created_at'},
  contests:{table:'contests',fields:['name','description','category_id','type','entry_fee','currency','status','max_participants','starting_time','ending_time'],owner:true,select:'c.id,c.creator_id,c.name,c.description,c.category_id,i.name category_name,u.name creator_name,c.type::text type,c.entry_fee,c.currency,c.status::text status,c.max_participants,c.starting_time,c.ending_time,c.created_at,(SELECT count(*) FROM contest_participants p WHERE p.contest_id=c.id) participant_count',from:'contests c JOIN users u ON u.id=c.creator_id JOIN interest_categories i ON i.id=c.category_id',search:['c.name','u.name','i.name','c.description'],statusField:'c.status',statusValues:['draft','published','cancelled','completed'],sortable:{created_at:'c.created_at',name:'c.name',status:'c.status',starting_time:'c.starting_time'},defaultSort:'c.created_at'},
  webinars:{table:'webinars',fields:['name','description','category_id','meeting_url','capacity','status','starting_time','ending_time'],owner:true,select:'w.id,w.creator_id,w.name,w.description,w.category_id,i.name category_name,u.name creator_name,w.meeting_url,w.capacity,w.status::text status,w.starting_time,w.ending_time,w.created_at,(SELECT count(*) FROM webinar_participants p WHERE p.webinar_id=w.id AND p.status IN (\'registered\',\'attended\')) participant_count',from:'webinars w JOIN users u ON u.id=w.creator_id JOIN interest_categories i ON i.id=w.category_id',search:['w.name','u.name','i.name','w.description'],statusField:'w.status',statusValues:['draft','scheduled','live','completed','cancelled'],sortable:{created_at:'w.created_at',name:'w.name',status:'w.status',starting_time:'w.starting_time'},defaultSort:'w.created_at'},
  jobs:{table:'jobs',fields:['title','description','type','status','location','is_remote','salary_min','salary_max','currency','salary_period','application_deadline','category_id'],owner:true,select:'j.id,j.creator_id,j.title,j.description,j.type::text type,j.status::text status,j.location,j.is_remote,j.salary_min,j.salary_max,j.currency,j.salary_period,j.application_deadline,j.category_id,i.name category_name,u.name creator_name,j.created_at,(SELECT count(*) FROM job_applications a WHERE a.job_id=j.id) application_count',from:'jobs j JOIN users u ON u.id=j.creator_id LEFT JOIN interest_categories i ON i.id=j.category_id',search:['j.title','u.name','j.location','i.name','j.description'],statusField:'j.status',statusValues:['draft','open','closed','filled','cancelled'],sortable:{created_at:'j.created_at',title:'j.title',status:'j.status',application_deadline:'j.application_deadline'},defaultSort:'j.created_at'},
  communities:{table:'communities',fields:['name','slug','description','category_id','requires_approval','is_private'],owner:true,select:'c.id,c.creator_id,c.name,c.slug,c.description,c.category_id,i.name category_name,u.name creator_name,c.requires_approval,c.is_private,c.created_at,(SELECT count(*) FROM community_members m WHERE m.community_id=c.id AND m.status=\'approved\') member_count',from:'communities c JOIN users u ON u.id=c.creator_id JOIN interest_categories i ON i.id=c.category_id',search:['c.name','c.slug','u.name','i.name','c.description'],sortable:{created_at:'c.created_at',name:'c.name'},defaultSort:'c.created_at'},
  showcase_posts:{table:'showcase_posts',fields:['content','visibility'],select:'p.id,p.creator_id,p.content,p.visibility::text visibility,p.created_at,p.deleted_at,u.name creator_name,i.name category_name',from:'showcase_posts p JOIN users u ON u.id=p.creator_id JOIN interest_categories i ON i.id=p.category_id',where:'p.deleted_at IS NULL',search:['p.content','u.name','i.name'],statusField:'p.visibility',statusValues:['public','private'],sortable:{created_at:'p.created_at',visibility:'p.visibility'},defaultSort:'p.created_at'},
  reported_showcase_posts:{table:'reported_showcase_posts',fields:['status','resolution_note'],select:'r.id,r.post_id,r.reporter_id,r.reason,r.details,r.status::text status,r.resolution_note,r.created_at,p.deleted_at,p.content post_content,u.name reporter_name,creator.name post_creator_name',from:'reported_showcase_posts r JOIN showcase_posts p ON p.id=r.post_id JOIN users u ON u.id=r.reporter_id JOIN users creator ON creator.id=p.creator_id',search:['r.reason','r.details','p.content','u.name','creator.name'],statusField:'r.status',statusValues:['pending','reviewing','resolved','dismissed'],sortable:{created_at:'r.created_at',status:'r.status',reason:'r.reason'},defaultSort:'r.created_at'}
};
const managedConfig=req=>{admin(req);const cfg=managed[req.params.table];if(!cfg)throw new ApiError(404,'Unknown collection');return cfg;};

const instructorImageTypes=new Set(['image/jpeg','image/png','image/webp','image/avif']);
function checkInstructorImage(file){if(!file)throw new ApiError(422,'Choose an instructor image');if(!instructorImageTypes.has(file.mimetype))throw new ApiError(422,'Use a JPEG, PNG, WebP, or AVIF image');}
function instructorLinks(body){const links={};for(const key of ['linkedin','github','website']){const value=body[`${key}_url`]?.trim();if(!value)continue;let parsed;try{parsed=new URL(value);}catch{throw new ApiError(422,`Enter a complete URL for ${key}`);}if(!['http:','https:'].includes(parsed.protocol))throw new ApiError(422,`Use an https:// or http:// URL for ${key}`);links[key]=parsed.toString();}return links;}
const instructorFields={name:z.string().trim().min(2).max(150),designation:z.string().trim().max(150).default(''),details:z.string().trim().max(10000).default(''),linkedin_url:z.string().trim().max(500).default(''),github_url:z.string().trim().max(500).default(''),website_url:z.string().trim().max(500).default(''),remove_image:z.enum(['true','false']).optional()};
app.post('/admin/instructors',upload.single('image'),run(async req=>{admin(req);checkInstructorImage(req.file);const instructor=z.object(instructorFields).strict().parse(req.body);const socialLinks=instructorLinks(instructor);return(await query('INSERT INTO instructors(name,designation,image_blob,image_mime_type,details,social_links) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,designation,details,social_links,image_mime_type,(image_blob IS NOT NULL) has_image,created_at',[instructor.name,instructor.designation,req.file.buffer,req.file.mimetype,instructor.details,JSON.stringify(socialLinks)])).rows[0];}));
app.patch('/admin/instructors/:id',upload.single('image'),run(async req=>{admin(req);const id=uuid(req.params.id);const body=z.object({...instructorFields,name:instructorFields.name.optional(),designation:instructorFields.designation.optional(),details:instructorFields.details.optional(),linkedin_url:instructorFields.linkedin_url.optional(),github_url:instructorFields.github_url.optional(),website_url:instructorFields.website_url.optional()}).strict().parse(req.body);if(req.file)checkInstructorImage(req.file);const fields=[],values=[];const add=(field,value)=>{fields.push(`${field}=$${values.length+1}`);values.push(value);};if(body.name!==undefined)add('name',body.name);if(body.designation!==undefined)add('designation',body.designation);if(body.details!==undefined)add('details',body.details);if(['linkedin_url','github_url','website_url'].some(key=>body[key]!==undefined))add('social_links',JSON.stringify(instructorLinks({...body,linkedin_url:body.linkedin_url||'',github_url:body.github_url||'',website_url:body.website_url||''})));if(req.file){add('image_blob',req.file.buffer);add('image_mime_type',req.file.mimetype);}else if(body.remove_image==='true'){add('image_blob',null);add('image_mime_type',null);}if(!fields.length)throw new ApiError(422,'Update a profile field or choose a new image');values.push(id);const result=await query(`UPDATE instructors SET ${fields.join(',')} WHERE id=$${values.length} RETURNING id,name,designation,details,social_links,image_mime_type,(image_blob IS NOT NULL) has_image,created_at`,values);if(!result.rowCount)throw new ApiError(404,'Instructor not found');return result.rows[0];}));
app.delete('/admin/instructors/:id',run(async req=>{admin(req);const id=uuid(req.params.id);const courses=Number((await query('SELECT count(*) FROM courses WHERE instructor_id=$1',[id])).rows[0].count);const result=await query('DELETE FROM instructors WHERE id=$1 RETURNING id',[id]);if(!result.rowCount)throw new ApiError(404,'Instructor not found');return{deleted:true,unassigned_courses:courses};}));

app.get('/admin/settings',run(async req=>{admin(req);const rows=(await query("SELECT key,value FROM platform_settings WHERE key IN ('registration_open','content_review_required')")).rows;const values={registration_open:true,content_review_required:true};for(const row of rows)values[row.key]=row.value===true;return values;}));
app.patch('/admin/settings',run(async req=>{admin(req);const settings=z.object({registration_open:z.boolean().optional(),content_review_required:z.boolean().optional()}).strict().refine(value=>Object.keys(value).length>0).parse(req.body);const descriptions={registration_open:'Allow public self-registration.',content_review_required:'Require admin approval before creators publish courses, contests, webinars or jobs.'};for(const[key,value]of Object.entries(settings))await query('INSERT INTO platform_settings(key,value,description,updated_by) VALUES($1,$2::jsonb,$3,$4) ON CONFLICT(key) DO UPDATE SET value=EXCLUDED.value,description=EXCLUDED.description,updated_by=EXCLUDED.updated_by,updated_at=now()',[key,JSON.stringify(value),descriptions[key],req.user.sub]);return settings;}));
app.get('/admin/overview',run(async req=>{admin(req);const stats=await one(`SELECT (SELECT count(*) FROM users) total_users,(SELECT count(*) FROM users WHERE role='learner') learners,(SELECT count(*) FROM users WHERE role='hirer') hirers,(SELECT count(*) FROM users WHERE account_status='active') active_users,(SELECT count(*) FROM courses) courses,(SELECT count(*) FROM courses WHERE status='published') published_courses,(SELECT count(*) FROM courses WHERE status='draft') draft_courses,(SELECT count(*) FROM contests) contests,(SELECT count(*) FROM contests WHERE status='published') published_contests,(SELECT count(*) FROM webinars) webinars,(SELECT count(*) FROM webinars WHERE status IN('scheduled','live')) active_webinars,(SELECT count(*) FROM jobs) jobs,(SELECT count(*) FROM jobs WHERE status='open') open_jobs,(SELECT count(*) FROM reported_showcase_posts WHERE status IN('pending','reviewing')) open_reports`);const activity=(await query(`SELECT * FROM(SELECT id::text id,'user'::text kind,'New account registered'::text title,name::text detail,created_at occurred_at FROM users UNION ALL SELECT id::text id,'course'::text kind,'Course created'::text title,title::text detail,created_at occurred_at FROM courses UNION ALL SELECT id::text id,'contest'::text kind,'Contest created'::text title,name::text detail,created_at occurred_at FROM contests UNION ALL SELECT id::text id,'webinar'::text kind,'Webinar created'::text title,name::text detail,created_at occurred_at FROM webinars UNION ALL SELECT id::text id,'job'::text kind,'Job posted'::text title,title::text detail,created_at occurred_at FROM jobs UNION ALL SELECT id::text id,'report'::text kind,'Post reported'::text title,reason::text detail,created_at occurred_at FROM reported_showcase_posts) activity ORDER BY occurred_at DESC LIMIT 12`)).rows;return{stats,activity};}));
app.get('/admin/:table',run(async req=>{const cfg=managedConfig(req);const[limit,offset]=paging(req);const values=[];const where=[cfg.where||'TRUE'];const add=value=>{values.push(value);return`$${values.length}`;};const search=String(req.query.q||'').trim().slice(0,200);if(search&&cfg.search?.length){const key=add(`%${search}%`);where.push(`(${cfg.search.map(field=>`${field}::text ILIKE ${key}`).join(' OR ')})`);}if(req.query.status){if(!cfg.statusField||!cfg.statusValues?.includes(String(req.query.status)))throw new ApiError(422,'Invalid status filter');where.push(`${cfg.statusField}::text=${add(String(req.query.status))}`);}const created=cfg.sortable?.created_at||'created_at';for(const field of ['from','to'])if(req.query[field]){const day=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).parse(String(req.query[field]));where.push(field==='from'?`${created}>=${add(day)}::date`:`${created}<(${add(day)}::date + interval '1 day')`);}const sort=cfg.sortable?.[String(req.query.sort||'')]||cfg.defaultSort||created;const direction=req.query.direction==='asc'?'ASC':'DESC';values.push(limit,offset);return(await query(`SELECT ${cfg.select||['id',...cfg.fields].join(',')} FROM ${cfg.from||cfg.table} WHERE ${where.join(' AND ')} ORDER BY ${sort} ${direction} NULLS LAST LIMIT $${values.length-1} OFFSET $${values.length}`,values)).rows;}));
app.post('/admin/users',run(async req=>{admin(req);const user=z.object({name:z.string().trim().min(2).max(150),email:z.string().trim().email().max(254),username:z.string().regex(/^[A-Za-z0-9_.-]{3,40}$/),password:z.string().min(8).max(128),role:z.enum(['learner','hirer','admin'])}).parse(req.body);const hash=await bcrypt.hash(user.password,12);try{return(await query('INSERT INTO users(name,email,username,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,username,role::text role,account_status::text account_status,created_at',[user.name,user.email,user.username,hash,user.role])).rows[0];}catch(error){if(error.code==='23505')throw new ApiError(409,'That email or username is already in use');throw error;}}));
app.post('/admin/:table/bulk',run(async req=>{const cfg=managedConfig(req);const body=z.object({ids:z.array(z.string().uuid()).min(1).max(100),action:z.enum(['status','delete']),status:z.string().optional()}).parse(req.body);if(body.action==='status'){if(!cfg.statusField||!cfg.statusValues?.includes(body.status))throw new ApiError(422,'This status is not available for the selected records');if(cfg.table==='users'&&body.ids.includes(req.user.sub)&&body.status!=='active')throw new ApiError(409,'You cannot disable your own admin account');const column=cfg.statusField.split('.').at(-1);const sets=[`${column}=$1`];const values=[cfg.table==='interest_categories'?body.status==='true':body.status,body.ids];if(cfg.table==='reported_showcase_posts'){sets.push('reviewed_by=$3','reviewed_at=now()');values.push(req.user.sub);}const result=await query(`UPDATE ${cfg.table} SET ${sets.join(',')} WHERE id=ANY($2::uuid[])`,values);return{updated:result.rowCount};}if(cfg.table==='users')throw new ApiError(409,'Suspend accounts instead of deleting user history');if(cfg.table==='showcase_posts'){const result=await query('UPDATE showcase_posts SET deleted_at=now() WHERE id=ANY($1::uuid[]) AND deleted_at IS NULL',[body.ids]);return{updated:result.rowCount};}const result=await query(`DELETE FROM ${cfg.table} WHERE id=ANY($1::uuid[])`,[body.ids]);return{updated:result.rowCount};}));
app.post('/admin/:table',upload.single('cover_image'),run(async req=>{const cfg=managedConfig(req);if(['users','showcase_posts','reported_showcase_posts','instructors'].includes(cfg.table))throw new ApiError(403,'Creation is not supported for this collection');const body=Object.fromEntries(cfg.fields.filter(key=>req.body[key]!==undefined).map(key=>[key,req.body[key]]));if(cfg.owner)body.creator_id=req.user.sub;if(cfg.table==='courses'){if(!body.instructor_id)throw new ApiError(422,'Assign an instructor before creating a course');body.instructor_id=uuid(body.instructor_id);if(!body.title||!body.slug||!body.description||!body.category_id)throw new ApiError(422,'Course title, slug, description, and interest are required');if(req.file){checkInstructorImage(req.file);body.cover_image=req.file.buffer;body.cover_image_mime_type=req.file.mimetype;}if(body.status==='published')body.published_at=new Date();}if(cfg.statusField&&body[cfg.statusField.split('.').at(-1)]!==undefined&&!cfg.statusValues?.includes(String(body[cfg.statusField.split('.').at(-1)])))throw new ApiError(422,'Invalid status');const keys=Object.keys(body);if(!keys.length)throw new ApiError(422,'No fields');return(await query(`INSERT INTO ${cfg.table}(${keys.join(',')}) VALUES(${keys.map((_,index)=>`$${index+1}`).join(',')}) RETURNING id`,Object.values(body))).rows[0];}));
app.patch('/admin/:table/:id',upload.single('cover_image'),run(async req=>{const cfg=managedConfig(req);uuid(req.params.id);const body=Object.fromEntries(cfg.fields.filter(key=>req.body[key]!==undefined).map(key=>[key,req.body[key]]));if(cfg.table==='courses'){if(body.instructor_id!==undefined)body.instructor_id=uuid(body.instructor_id);const removeCover=req.body.remove_cover_image;if(removeCover!==undefined&&!['true','false'].includes(removeCover))throw new ApiError(422,'Invalid remove cover flag');if(req.file){checkInstructorImage(req.file);body.cover_image=req.file.buffer;body.cover_image_mime_type=req.file.mimetype;}else if(removeCover==='true'){body.cover_image=null;body.cover_image_mime_type=null;}}if(cfg.table==='users'){if(body.role!==undefined&&!z.enum(['learner','hirer','moderator','admin']).safeParse(body.role).success)throw new ApiError(422,'Invalid user role');if(body.name!==undefined)body.name=z.string().trim().min(2).max(150).parse(body.name);if(body.email!==undefined)body.email=z.string().trim().email().max(254).parse(body.email);if(body.username!==undefined)body.username=z.string().regex(/^[A-Za-z0-9_.-]{3,40}$/).parse(body.username);if(body.account_status!==undefined)z.enum(['active','suspended','deactivated']).parse(body.account_status);if(req.params.id===req.user.sub&&(body.role&&body.role!=='admin'||body.account_status&&body.account_status!=='active'))throw new ApiError(409,'You cannot disable or demote your own admin account');}if(cfg.statusField&&body[cfg.statusField.split('.').at(-1)]!==undefined&&!cfg.statusValues?.includes(String(body[cfg.statusField.split('.').at(-1)])))throw new ApiError(422,'Invalid status');if(cfg.table==='courses'&&body.status==='published'&&body.published_at===undefined)body.published_at=new Date();if(cfg.table==='reported_showcase_posts'){body.reviewed_by=req.user.sub;body.reviewed_at=new Date();}const keys=Object.keys(body);if(!keys.length)throw new ApiError(422,'No fields');const values=[...Object.values(body),req.params.id];const result=await query(`UPDATE ${cfg.table} SET ${keys.map((key,index)=>`${key}=$${index+1}`).join(',')} WHERE id=$${keys.length+1}`,values);if(!result.rowCount)throw new ApiError(404,'Record not found');}));
app.delete('/admin/:table/:id',run(async req=>{const cfg=managedConfig(req);const id=uuid(req.params.id);if(cfg.table==='users')throw new ApiError(409,'Suspend accounts instead of deleting user history');if(cfg.table==='showcase_posts'){const result=await query('UPDATE showcase_posts SET deleted_at=now() WHERE id=$1 AND deleted_at IS NULL',[id]);if(!result.rowCount)throw new ApiError(404,'Record not found');return;}const result=await query(`DELETE FROM ${cfg.table} WHERE id=$1`,[id]);if(!result.rowCount)throw new ApiError(404,'Record not found');}));
app.get('/manage/courses/:id/materials',run(async req=>{admin(req);return(await query('SELECT id,name,type,sort_order,content_text,external_url,is_preview FROM course_materials WHERE course_id=$1 ORDER BY sort_order',[uuid(req.params.id)])).rows;}));
app.post('/manage/courses/:id/materials',run(async req=>{admin(req);const b=z.object({name:z.string().min(1).max(250),content_text:z.string().min(1),is_preview:z.boolean()}).parse(req.body);return tx(async db=>{await db.query('SELECT id FROM courses WHERE id=$1 FOR UPDATE',[uuid(req.params.id)]);return(await db.query(`INSERT INTO course_materials(course_id,name,type,content_text,is_preview,sort_order) VALUES($1,$2,'text',$3,$4,(SELECT coalesce(max(sort_order),-1)+1 FROM course_materials WHERE course_id=$1)) RETURNING id`,[req.params.id,b.name,b.content_text,b.is_preview])).rows[0];});}));
app.get('/manage/contests/:id/problems',run(async req=>{admin(req);return(await query('SELECT id,name,description,points FROM contest_problems WHERE contest_id=$1 ORDER BY sort_order',[uuid(req.params.id)])).rows;}));
app.post('/manage/contests/:id/problems',run(async req=>{admin(req);const b=z.object({name:z.string().min(1),description:z.string().min(1),points:z.number().nonnegative()}).parse(req.body);return tx(async db=>{await db.query('SELECT id FROM contests WHERE id=$1 FOR UPDATE',[uuid(req.params.id)]);return(await db.query(`INSERT INTO contest_problems(creator_id,contest_id,name,description,points,sort_order) VALUES($1,$2,$3,$4,$5,(SELECT coalesce(max(sort_order),-1)+1 FROM contest_problems WHERE contest_id=$2)) RETURNING id`,[req.user.sub,req.params.id,b.name,b.description,b.points])).rows[0];});}));
app.get('/manage/contests/:id/submissions',run(async req=>{admin(req);return(await query('SELECT s.id,s.content,s.score,s.status,s.problem_id,u.name FROM contest_submissions s JOIN users u ON u.id=s.participant_id WHERE contest_id=$1 ORDER BY submitted_at DESC LIMIT 100',[uuid(req.params.id)])).rows;}));
app.patch('/manage/submissions/:id',run(async req=>{admin(req);const b=z.object({score:z.number().nonnegative(),status:z.enum(['accepted','rejected','disqualified','judging'])}).parse(req.body);await tx(async db=>{const sub=(await db.query('SELECT contest_id,participant_id FROM contest_submissions WHERE id=$1',[uuid(req.params.id)])).rows[0];if(!sub)throw new ApiError(404,'Submission not found');await db.query('SELECT 1 FROM contest_participants WHERE contest_id=$1 AND participant_id=$2 FOR UPDATE',[sub.contest_id,sub.participant_id]);await db.query('UPDATE contest_submissions SET score=$1,status=$2,judged_at=now(),judged_by=$3 WHERE id=$4',[b.score,b.status,req.user.sub,req.params.id]);await db.query(`UPDATE contest_participants SET points=(SELECT coalesce(sum(best),0) FROM(SELECT max(score) best FROM contest_submissions WHERE contest_id=$1 AND participant_id=$2 AND status='accepted' GROUP BY problem_id) scores) WHERE contest_id=$1 AND participant_id=$2`,[sub.contest_id,sub.participant_id]);});}));
listen(app,process.env.FRONTEND_API_PORT||4010,'frontend-api');
