import express from 'express';
import {z} from 'zod';
import {createApp,query,tx,asyncHandler,auth,allow,ApiError,listen} from '@uddeepto/common';
const app=createApp('frontend-api');
app.use(auth());
// Look up current roles and account state; never authorize from a stale role claim.
app.use(asyncHandler(async(req,_res,next)=>{const u=(await query('SELECT id,role,account_status FROM users WHERE id=$1',[req.user.sub])).rows[0];if(!u||u.account_status!=='active')throw new ApiError(401,'Account is not active');req.user.role=u.role;next();}));
const run=fn=>asyncHandler(async(req,res)=>{const value=await fn(req,res);if(!res.headersSent)res.json(value??{ok:true});});
const uuid=v=>z.string().uuid().parse(v);
const text=v=>z.string().trim().min(1).max(10000).parse(v);
const paging=req=>[Math.min(100,Math.max(1,parseInt(req.query.limit)||20)),Math.max(0,parseInt(req.query.offset)||0)];
const admin=req=>{if(req.user.role!=='admin')throw new ApiError(403,'Admin required');};
const learner=req=>{if(req.user.role==='hirer')throw new ApiError(403,'Learner permission required');};
const one=async(sql,args)=>{const r=await query(sql,args);if(!r.rowCount)throw new ApiError(404,'Not found');return r.rows[0];};
const ownJob=async req=>{const j=await one('SELECT creator_id FROM jobs WHERE id=$1',[uuid(req.params.id)]);if(j.creator_id!==req.user.sub&&req.user.role!=='admin')throw new ApiError(403,'Only the job owner can view applications');};
async function communityAccess(req){const c=await one(`SELECT c.*,m.status membership,m.is_moderator FROM communities c LEFT JOIN community_members m ON m.community_id=c.id AND m.member_id=$2 WHERE c.id=$1`,[uuid(req.params.id),req.user.sub]);c.can_manage=c.creator_id===req.user.sub||req.user.role==='admin'||(c.membership==='approved'&&c.is_moderator);if(c.creator_id===req.user.sub||req.user.role==='admin')c.membership='approved';return c;}
async function requireMember(req){const c=await communityAccess(req);if(c.membership!=='approved')throw new ApiError(403,'Approved membership required');return c;}
async function conversationAccess(req){await one('SELECT 1 FROM conversation_members WHERE conversation_id=$1 AND user_id=$2',[uuid(req.params.id),req.user.sub]);}
app.get('/dashboard',run(async req=>{
  const id=req.user.sub;
  if(req.user.role==='hirer')return {...(await one(`SELECT (SELECT count(*) FROM jobs WHERE creator_id=$1) jobs,(SELECT count(*) FROM jobs WHERE creator_id=$1 AND status='open') open_jobs,(SELECT count(*) FROM job_applications a JOIN jobs j ON j.id=a.job_id WHERE j.creator_id=$1) applications,(SELECT count(*) FROM showcase_posts WHERE creator_id=$1 AND deleted_at IS NULL) posts`,[id])),recent:(await query('SELECT j.title,a.status FROM job_applications a JOIN jobs j ON j.id=a.job_id WHERE j.creator_id=$1 ORDER BY a.applied_at DESC LIMIT 5',[id])).rows};
  return {...(await one(`SELECT (SELECT count(*) FROM course_enrollments WHERE user_id=$1 AND status IN ('active','completed')) enrollments,(SELECT count(*) FROM contest_participants WHERE participant_id=$1) contests,(SELECT count(*) FROM community_members WHERE member_id=$1 AND status='approved') communities,(SELECT count(*) FROM job_applications WHERE applicant_id=$1) applications`,[id])),recent:(await query(`SELECT c.title,e.status FROM course_enrollments e JOIN courses c ON c.id=e.course_id WHERE e.user_id=$1 AND e.status IN('active','completed') ORDER BY e.enrolled_at DESC LIMIT 5`,[id])).rows,upcoming:(await query(`SELECT id,name,status,starting_time FROM webinars WHERE status='scheduled' AND starting_time>now() ORDER BY starting_time LIMIT 3`)).rows};
}));
app.get('/people',run(async req=>(await query(`SELECT id,name,username,role FROM users WHERE account_status='active' AND (name ILIKE $1 OR username::text ILIKE $1) ORDER BY name LIMIT 30`,[`%${String(req.query.q||'').slice(0,100)}%`])).rows));
app.get('/profile/:id',run(async req=>{const p=await one(`SELECT id,name,username,bio,role,created_at FROM users WHERE id=$1 AND account_status='active'`,[uuid(req.params.id)]);p.interests=(await query('SELECT i.id,i.name FROM user_interests ui JOIN interest_categories i ON i.id=ui.interest_id WHERE ui.user_id=$1',[p.id])).rows;p.posts=(await query(`SELECT id,content FROM showcase_posts WHERE creator_id=$1 AND deleted_at IS NULL AND visibility='public' ORDER BY created_at DESC LIMIT 12`,[p.id])).rows;return p;}));
app.patch('/profile',run(async req=>{const b=z.object({name:z.string().trim().min(2).max(150),username:z.string().regex(/^[A-Za-z0-9_.-]{3,40}$/),bio:z.string().max(3000),interest_ids:z.array(z.string().uuid()).max(30)}).parse(req.body);await tx(async db=>{await db.query('UPDATE users SET name=$1,username=$2,bio=$3 WHERE id=$4',[b.name,b.username,b.bio,req.user.sub]);await db.query('DELETE FROM user_interests WHERE user_id=$1',[req.user.sub]);for(const id of new Set(b.interest_ids))await db.query('INSERT INTO user_interests(user_id,interest_id) VALUES($1,$2)',[req.user.sub,id]);});}));
app.get('/showcase',run(async req=>{const[limit,offset]=paging(req);return(await query(`SELECT p.id,p.creator_id,p.content,p.created_at,u.name creator_name,i.name category_name,(SELECT count(*) FROM showcase_post_reactions WHERE post_id=p.id) reactions,(SELECT count(*) FROM showcase_post_comments WHERE post_id=p.id AND deleted_at IS NULL) comments,EXISTS(SELECT 1 FROM showcase_post_reactions WHERE post_id=p.id AND user_id=$1 AND reaction='love') my_reaction FROM showcase_posts p JOIN users u ON u.id=p.creator_id JOIN interest_categories i ON i.id=p.category_id WHERE p.deleted_at IS NULL AND p.visibility='public' AND p.content ILIKE $2 AND($3::uuid IS NULL OR p.category_id=$3) ORDER BY p.created_at DESC LIMIT $4 OFFSET $5`,[req.user.sub,`%${String(req.query.q||'').slice(0,200)}%`,req.query.category?uuid(req.query.category):null,limit,offset])).rows;}));
async function visiblePost(id){return one(`SELECT id FROM showcase_posts WHERE id=$1 AND visibility='public' AND deleted_at IS NULL`,[uuid(id)]);}
app.delete('/showcase/:id',run(async req=>{const r=await query('UPDATE showcase_posts SET deleted_at=now() WHERE id=$1 AND(creator_id=$2 OR $3=\'admin\') RETURNING id',[uuid(req.params.id),req.user.sub,req.user.role]);if(!r.rowCount)throw new ApiError(403,'Not your post');}));
async function toggleReaction(table,field,id,user){await tx(async db=>{await db.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`${table}:${id}:${user}`]);const removed=await db.query(`DELETE FROM ${table} WHERE ${field}=$1 AND user_id=$2 AND reaction='love'`,[id,user]);if(!removed.rowCount)await db.query(`INSERT INTO ${table}(${field},user_id,reaction) VALUES($1,$2,'love')`,[id,user]);});}
app.put('/showcase/:id/reaction',run(async req=>{await visiblePost(req.params.id);await toggleReaction('showcase_post_reactions','post_id',req.params.id,req.user.sub);}));
app.get('/showcase/:id/comments',run(async req=>{await visiblePost(req.params.id);return(await query(`SELECT c.id,c.commenter_id,c.content,u.name,(SELECT count(*) FROM showcase_post_comment_reactions WHERE comment_id=c.id) reactions,EXISTS(SELECT 1 FROM showcase_post_comment_reactions WHERE comment_id=c.id AND user_id=$2 AND reaction='love') my_reaction FROM showcase_post_comments c JOIN users u ON u.id=c.commenter_id WHERE c.post_id=$1 AND c.deleted_at IS NULL ORDER BY c.created_at LIMIT 100`,[req.params.id,req.user.sub])).rows;}));
app.post('/showcase/:id/comments',run(async req=>{await visiblePost(req.params.id);return(await query('INSERT INTO showcase_post_comments(post_id,commenter_id,content) VALUES($1,$2,$3) RETURNING id',[req.params.id,req.user.sub,text(req.body.content)])).rows[0];}));
app.put('/comments/:id/reaction',run(async req=>{const c=await one('SELECT post_id FROM showcase_post_comments WHERE id=$1 AND deleted_at IS NULL',[uuid(req.params.id)]);await visiblePost(c.post_id);await toggleReaction('showcase_post_comment_reactions','comment_id',req.params.id,req.user.sub);}));
const catalogs={courses:{title:'title',columns:'price,currency,slug',visible:"status='published'"},contests:{title:'name',columns:'entry_fee,currency,starting_time,ending_time',visible:"status IN ('published','completed','cancelled')"},webinars:{title:'name',columns:'starting_time,ending_time',visible:"status IN ('scheduled','live','completed','cancelled')"},communities:{title:'name',columns:'slug,is_private',visible:'true'}};
app.get('/catalog/:kind',run(async req=>{learner(req);const{kind}=req.params;const cfg=catalogs[kind];if(!cfg)throw new ApiError(404,'Unknown catalog');const[limit,offset]=paging(req);const args=[req.user.sub,`%${String(req.query.q||'').slice(0,200)}%`,req.query.category?uuid(req.query.category):null,limit,offset];let filter=`t.${cfg.visible}`;if(kind==='communities')filter='true';if(req.query.tab==='enrolled'&&kind==='courses')filter+=` AND EXISTS(SELECT 1 FROM course_enrollments WHERE course_id=t.id AND user_id=$1 AND status IN('active','completed'))`;if(['webinars','contests'].includes(kind)){const tab=req.query.tab;if(tab==='ongoing')filter+=` AND starting_time<=now() AND ending_time>=now() AND t.status NOT IN('completed','cancelled')`;if(tab==='upcoming')filter+=` AND starting_time>now() AND t.status NOT IN('completed','cancelled')`;if(tab==='previous')filter+=` AND(ending_time<now() OR t.status IN('completed','cancelled'))`;}
 const extras=kind==='courses'?`,EXISTS(SELECT 1 FROM course_enrollments WHERE course_id=t.id AND user_id=$1 AND status IN('active','completed')) enrolled`:kind==='communities'?`,(SELECT count(*) FROM community_members WHERE community_id=t.id AND status='approved') member_count,($1::uuid IS NOT NULL) authenticated`:',($1::uuid IS NOT NULL) authenticated';
 return(await query(`SELECT t.id,t.${cfg.title},t.description,${kind==='communities'?"'active' AS status":'t.status'},${cfg.columns.split(',').map(c=>'t.'+c).join(',')},u.name creator_name,i.name category_name ${extras} FROM ${kind} t JOIN users u ON u.id=t.creator_id JOIN interest_categories i ON i.id=t.category_id WHERE ${filter} AND(t.${cfg.title} ILIKE $2 OR t.description ILIKE $2) AND($3::uuid IS NULL OR t.category_id=$3) ORDER BY t.created_at DESC LIMIT $4 OFFSET $5`,args)).rows;
}));
app.get('/detail/:kind/:id',run(async req=>{learner(req);const{kind}=req.params;uuid(req.params.id);if(!['courses','contests','webinars'].includes(kind))throw new ApiError(404,'Unknown kind');const cfg=catalogs[kind];const t=await one(`SELECT id,creator_id FROM ${kind} WHERE id=$1 AND(${cfg.visible} OR creator_id=$2 OR $3='admin')`,[req.params.id,req.user.sub,req.user.role]);if(kind==='courses'){const enrollment=await query(`SELECT status FROM course_enrollments WHERE course_id=$1 AND user_id=$2 AND status IN('active','completed')`,[t.id,req.user.sub]);return{enrolled:!!enrollment.rowCount,materials:(await query(`SELECT m.id,m.name,m.is_preview,m.content_blob IS NOT NULL has_blob,EXISTS(SELECT 1 FROM completed_course_materials WHERE material_id=m.id AND user_id=$2) completed FROM course_materials m WHERE course_id=$1 ORDER BY sort_order`,[t.id,req.user.sub])).rows};}const participants=await query(`SELECT 1 FROM ${kind==='contests'?'contest':'webinar'}_participants WHERE ${kind==='contests'?'contest':'webinar'}_id=$1 AND participant_id=$2 ${kind==='webinars'?"AND status IN('registered','attended')":"AND payment_status='paid'"}`,[t.id,req.user.sub]);if(kind==='webinars')return{joined:!!participants.rowCount,meeting_url:participants.rowCount?(await one('SELECT meeting_url FROM webinars WHERE id=$1',[t.id])).meeting_url:null};const started=await query('SELECT 1 FROM contests WHERE id=$1 AND starting_time<=now()',[t.id]);return{joined:!!participants.rowCount,problems:started.rowCount?(await query('SELECT id,name,description,points,sample_input,sample_output FROM contest_problems WHERE contest_id=$1 ORDER BY sort_order',[t.id])).rows:[],leaderboard:(await query('SELECT u.id,u.name,p.points FROM contest_participants p JOIN users u ON u.id=p.participant_id WHERE contest_id=$1 ORDER BY points DESC,participated_at LIMIT 50',[t.id])).rows};}));
app.put('/courses/:id/complete/:materialId',run(async req=>{learner(req);await tx(async db=>{const e=await db.query(`SELECT 1 FROM course_enrollments WHERE course_id=$1 AND user_id=$2 AND status IN('active','completed') FOR UPDATE`,[uuid(req.params.id),req.user.sub]);if(!e.rowCount)throw new ApiError(403,'Enrollment required');await db.query('INSERT INTO completed_course_materials(course_id,user_id,material_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING',[req.params.id,req.user.sub,uuid(req.params.materialId)]);await db.query(`UPDATE course_enrollments SET status='completed',completed_at=now() WHERE course_id=$1 AND user_id=$2 AND NOT EXISTS(SELECT 1 FROM course_materials m WHERE course_id=$1 AND NOT EXISTS(SELECT 1 FROM completed_course_materials WHERE material_id=m.id AND user_id=$2))`,[req.params.id,req.user.sub]);});}));
app.post('/webinars/:id/join',run(async req=>{learner(req);await tx(async db=>{const w=(await db.query('SELECT * FROM webinars WHERE id=$1 FOR UPDATE',[uuid(req.params.id)])).rows[0];if(!w||!['scheduled','live'].includes(w.status)||new Date(w.ending_time)<new Date())throw new ApiError(409,'Registration closed');const existing=await db.query(`SELECT 1 FROM webinar_participants WHERE webinar_id=$1 AND participant_id=$2 AND status IN('registered','attended')`,[w.id,req.user.sub]);if(existing.rowCount)return;const count=Number((await db.query(`SELECT count(*) FROM webinar_participants WHERE webinar_id=$1 AND status IN('registered','attended')`,[w.id])).rows[0].count);if(w.capacity&&count>=w.capacity)throw new ApiError(409,'Webinar is full');await db.query(`INSERT INTO webinar_participants(webinar_id,participant_id) VALUES($1,$2) ON CONFLICT(webinar_id,participant_id) DO UPDATE SET status='registered'`,[w.id,req.user.sub]);});}));
app.post('/contests/:id/join',run(async req=>{learner(req);await tx(async db=>{const c=(await db.query('SELECT * FROM contests WHERE id=$1 FOR UPDATE',[uuid(req.params.id)])).rows[0];if(!c||c.status!=='published'||new Date(c.ending_time)<new Date())throw new ApiError(409,'Contest unavailable');if(Number(c.entry_fee)>0)throw new ApiError(402,'Paid entries need a payment provider; contact the organizer.');if((await db.query('SELECT 1 FROM contest_participants WHERE contest_id=$1 AND participant_id=$2',[c.id,req.user.sub])).rowCount)return;const n=Number((await db.query('SELECT count(*) FROM contest_participants WHERE contest_id=$1',[c.id])).rows[0].count);if(c.max_participants&&n>=c.max_participants)throw new ApiError(409,'Contest is full');await db.query(`INSERT INTO contest_participants(contest_id,participant_id,payment_status) VALUES($1,$2,'paid')`,[c.id,req.user.sub]);});}));
app.post('/contests/:id/submit',run(async req=>{learner(req);const c=await one(`SELECT id FROM contests WHERE id=$1 AND status='published' AND starting_time<=now() AND ending_time>=now()`,[uuid(req.params.id)]);await one(`SELECT 1 FROM contest_participants WHERE contest_id=$1 AND participant_id=$2 AND payment_status='paid'`,[c.id,req.user.sub]);return(await query('INSERT INTO contest_submissions(contest_id,participant_id,problem_id,content) VALUES($1,$2,$3,$4) RETURNING id',[c.id,req.user.sub,req.body.problem_id?uuid(req.body.problem_id):null,text(req.body.content)])).rows[0];}));
app.post('/communities',run(async req=>{learner(req);const b=z.object({name:z.string().trim().min(2).max(150),slug:z.string().regex(/^[a-z0-9]+(-[a-z0-9]+)*$/),description:z.string().max(10000),category_id:z.string().uuid(),requires_approval:z.boolean(),is_private:z.boolean()}).parse(req.body);return tx(async db=>{const c=(await db.query('INSERT INTO communities(creator_id,name,slug,description,category_id,requires_approval,is_private) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[req.user.sub,b.name,b.slug,b.description,b.category_id,b.requires_approval,b.is_private])).rows[0];await db.query(`INSERT INTO community_members(community_id,member_id,status,is_moderator,approved_at,approved_by) VALUES($1,$2,'approved',true,now(),$2)`,[c.id,req.user.sub]);await db.query(`INSERT INTO community_chats(community_id,name) VALUES($1,'general')`,[c.id]);return c;});}));
app.get('/communities/:id',run(async req=>{learner(req);const c=await communityAccess(req);return{membership:c.membership,can_manage:c.can_manage,chats:c.membership==='approved'?(await query('SELECT id,name FROM community_chats WHERE community_id=$1 ORDER BY sort_order',[c.id])).rows:[],pending:c.can_manage?(await query(`SELECT m.member_id,u.name FROM community_members m JOIN users u ON u.id=m.member_id WHERE community_id=$1 AND status='pending' LIMIT 100`,[c.id])).rows:[]};}));
app.patch('/communities/:id/members/:userId',run(async req=>{learner(req);const c=await communityAccess(req);if(!c.can_manage)throw new ApiError(403,'Moderator required');const status=z.enum(['approved','rejected','blocked']).parse(req.body.status);await query(`UPDATE community_members SET status=$1,approved_at=CASE WHEN $1='approved' THEN now() ELSE NULL END,approved_by=$2 WHERE community_id=$3 AND member_id=$4`,[status,req.user.sub,c.id,uuid(req.params.userId)]);}));
app.post('/communities/:id/chats',run(async req=>{learner(req);const c=await communityAccess(req);if(!c.can_manage)throw new ApiError(403,'Moderator required');return(await query('INSERT INTO community_chats(community_id,name) VALUES($1,$2) RETURNING id',[c.id,z.string().trim().min(1).max(150).parse(req.body.name)])).rows[0];}));
app.get('/communities/:id/chats/:chatId',run(async req=>{learner(req);await requireMember(req);return(await query(`SELECT * FROM(SELECT m.id,m.content,m.created_at,u.name sender_name FROM community_chat_messages m JOIN users u ON u.id=m.sender_id WHERE community_id=$1 AND chat_id=$2 AND deleted_at IS NULL ORDER BY m.created_at DESC LIMIT 100) recent ORDER BY created_at`,[req.params.id,uuid(req.params.chatId)])).rows;}));
app.post('/communities/:id/chats/:chatId',run(async req=>{learner(req);await requireMember(req);return(await query('INSERT INTO community_chat_messages(community_id,chat_id,sender_id,content) VALUES($1,$2,$3,$4) RETURNING id',[req.params.id,uuid(req.params.chatId),req.user.sub,text(req.body.content)])).rows[0];}));
app.get('/jobs',run(async req=>{const[limit,offset]=paging(req);const tab=req.query.tab;const filter=tab==='mine'?`j.creator_id=$1`:tab==='applied'?`a.applicant_id=$1`:`j.status='open' AND(application_deadline IS NULL OR application_deadline>now())`;return(await query(`SELECT j.id,j.creator_id,j.title,j.description,j.status,j.type,j.salary_min,j.salary_max,j.currency,j.location,j.is_remote,j.application_deadline,u.name creator_name,a.status application_status FROM jobs j JOIN users u ON u.id=j.creator_id LEFT JOIN job_applications a ON a.job_id=j.id AND a.applicant_id=$1 WHERE ${filter} AND(j.title ILIKE $2 OR j.description ILIKE $2) AND($3='' OR j.type::text=$3) ORDER BY j.created_at DESC LIMIT $4 OFFSET $5`,[req.user.sub,`%${String(req.query.q||'').slice(0,200)}%`,req.query.type||'',limit,offset])).rows;}));
app.get('/jobs/:id/applications',run(async req=>{await ownJob(req);return(await query('SELECT a.applicant_id,a.status,a.cover_letter,a.applied_at,a.resume_blob IS NOT NULL has_resume,u.name,u.username FROM job_applications a JOIN users u ON u.id=a.applicant_id WHERE job_id=$1 ORDER BY applied_at DESC LIMIT 100',[req.params.id])).rows;}));
app.get('/jobs/:id/applications/:userId/resume',run(async(req,res)=>{await ownJob(req);const a=await one('SELECT resume_blob,resume_mime_type FROM job_applications WHERE job_id=$1 AND applicant_id=$2',[req.params.id,uuid(req.params.userId)]);if(!a.resume_blob)throw new ApiError(404,'Resume not found');res.set('Content-Disposition','attachment; filename="resume.pdf"').type('application/octet-stream').send(a.resume_blob);}));
app.patch('/jobs/:id/applications/:userId',run(async req=>{await ownJob(req);const status=z.enum(['shortlisted','accepted','rejected','applied']).parse(req.body.status);await query('UPDATE job_applications SET status=$1 WHERE job_id=$2 AND applicant_id=$3',[status,req.params.id,uuid(req.params.userId)]);}));
app.patch('/jobs/:id/status',run(async req=>{await ownJob(req);await query('UPDATE jobs SET status=$1 WHERE id=$2',[z.enum(['open','closed']).parse(req.body.status),req.params.id]);}));
app.get('/messages',run(async req=>{learner(req);return(await query(`SELECT c.id,c.updated_at,u.name,u.id other_user_id,(SELECT content FROM messages WHERE conversation_id=c.id AND deleted_at IS NULL ORDER BY sent_at DESC LIMIT 1) last_message FROM conversations c JOIN conversation_members mine ON mine.conversation_id=c.id AND mine.user_id=$1 JOIN conversation_members other ON other.conversation_id=c.id AND other.user_id<>$1 JOIN users u ON u.id=other.user_id WHERE (SELECT count(*) FROM conversation_members WHERE conversation_id=c.id)=2 ORDER BY c.updated_at DESC LIMIT 100`,[req.user.sub])).rows;}));
app.post('/messages',run(async req=>{learner(req);const other=uuid(req.body.user_id);if(other===req.user.sub)throw new ApiError(422,'Choose another person');await one(`SELECT id FROM users WHERE id=$1 AND account_status='active'`,[other]);return tx(async db=>{await db.query('SELECT pg_advisory_xact_lock(hashtext($1))',[[other,req.user.sub].sort().join(':')]);const found=await db.query(`SELECT a.conversation_id id FROM conversation_members a JOIN conversation_members b ON b.conversation_id=a.conversation_id WHERE a.user_id=$1 AND b.user_id=$2 AND (SELECT count(*) FROM conversation_members WHERE conversation_id=a.conversation_id)=2 LIMIT 1`,[req.user.sub,other]);if(found.rowCount)return found.rows[0];const c=(await db.query('INSERT INTO conversations DEFAULT VALUES RETURNING id')).rows[0];await db.query('INSERT INTO conversation_members(conversation_id,user_id) VALUES($1,$2),($1,$3)',[c.id,req.user.sub,other]);return c;});}));
app.get('/messages/:id',run(async req=>{learner(req);await conversationAccess(req);await query('UPDATE conversation_members SET last_read_at=now() WHERE conversation_id=$1 AND user_id=$2',[req.params.id,req.user.sub]);return(await query(`SELECT * FROM(SELECT id,sender_id,content,sent_at FROM messages WHERE conversation_id=$1 AND deleted_at IS NULL ORDER BY sent_at DESC LIMIT 100) latest ORDER BY sent_at`,[req.params.id])).rows;}));
app.post('/messages/:id',run(async req=>{learner(req);await conversationAccess(req);return tx(async db=>{const m=(await db.query('INSERT INTO messages(conversation_id,sender_id,content) VALUES($1,$2,$3) RETURNING id',[req.params.id,req.user.sub,text(req.body.content)])).rows[0];await db.query('UPDATE conversations SET updated_at=now() WHERE id=$1',[req.params.id]);return m;});}));
const managed={
users:{fields:['name','username','role','account_status'],select:'id,name,username,role,account_status'},
interest_categories:{fields:['name','slug','icon','description','is_active']},
courses:{fields:['title','slug','description','category_id','price','currency','status'],owner:true,select:'id,title,slug,description,category_id,price,currency,status'},
contests:{fields:['name','description','category_id','type','entry_fee','currency','status','max_participants','starting_time','ending_time'],owner:true},
webinars:{fields:['name','description','category_id','meeting_url','capacity','status','starting_time','ending_time'],owner:true},
communities:{fields:['name','slug','description','category_id','requires_approval','is_private'],owner:true,select:'id,name,slug,description,category_id,requires_approval,is_private'},
jobs:{fields:['title','description','type','status','location','is_remote'],owner:true},
showcase_posts:{fields:['content','visibility'],select:'id,content,visibility'},
reported_showcase_posts:{fields:['status','resolution_note']}
};
const managedConfig=req=>{admin(req);const cfg=managed[req.params.table];if(!cfg)throw new ApiError(404,'Unknown collection');return cfg;};
app.get('/admin/:table',run(async req=>{const cfg=managedConfig(req);const[limit,offset]=paging(req);return(await query(`SELECT ${cfg.select||['id',...cfg.fields].join(',')} FROM ${req.params.table} ORDER BY created_at DESC LIMIT $1 OFFSET $2`,[limit,offset])).rows;}));
app.post('/admin/:table',run(async req=>{const cfg=managedConfig(req);if(['users','showcase_posts','reported_showcase_posts'].includes(req.params.table))throw new ApiError(403,'Creation not supported here');const b=Object.fromEntries(cfg.fields.filter(k=>req.body[k]!==undefined).map(k=>[k,req.body[k]]));if(cfg.owner)b.creator_id=req.user.sub;const keys=Object.keys(b);if(!keys.length)throw new ApiError(422,'No fields');return(await query(`INSERT INTO ${req.params.table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>`$${i+1}`).join(',')}) RETURNING id`,Object.values(b))).rows[0];}));
app.patch('/admin/:table/:id',run(async req=>{const cfg=managedConfig(req);uuid(req.params.id);const b=Object.fromEntries(cfg.fields.filter(k=>req.body[k]!==undefined).map(k=>[k,req.body[k]]));if(req.params.table==='users'){if(b.role!==undefined)z.enum(['learner','hirer','admin']).parse(b.role);if(req.params.id===req.user.sub&&(b.role&&b.role!=='admin'||b.account_status&&b.account_status!=='active'))throw new ApiError(409,'You cannot disable or demote your own admin account');}if(req.params.table==='reported_showcase_posts'){b.reviewed_by=req.user.sub;b.reviewed_at=new Date();}const keys=Object.keys(b);if(!keys.length)throw new ApiError(422,'No fields');await query(`UPDATE ${req.params.table} SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')} WHERE id=$${keys.length+1}`,[...Object.values(b),req.params.id]);}));
app.delete('/admin/:table/:id',run(async req=>{managedConfig(req);if(req.params.table==='users')throw new ApiError(409,'Suspend accounts instead of deleting user history');await query(`DELETE FROM ${req.params.table} WHERE id=$1`,[uuid(req.params.id)]);}));
app.get('/manage/courses/:id/materials',run(async req=>{admin(req);return(await query('SELECT id,name,type,sort_order,content_text,external_url,is_preview FROM course_materials WHERE course_id=$1 ORDER BY sort_order',[uuid(req.params.id)])).rows;}));
app.post('/manage/courses/:id/materials',run(async req=>{admin(req);const b=z.object({name:z.string().min(1).max(250),content_text:z.string().min(1),is_preview:z.boolean()}).parse(req.body);return tx(async db=>{await db.query('SELECT id FROM courses WHERE id=$1 FOR UPDATE',[uuid(req.params.id)]);return(await db.query(`INSERT INTO course_materials(course_id,name,type,content_text,is_preview,sort_order) VALUES($1,$2,'text',$3,$4,(SELECT coalesce(max(sort_order),-1)+1 FROM course_materials WHERE course_id=$1)) RETURNING id`,[req.params.id,b.name,b.content_text,b.is_preview])).rows[0];});}));
app.get('/manage/contests/:id/problems',run(async req=>{admin(req);return(await query('SELECT id,name,description,points FROM contest_problems WHERE contest_id=$1 ORDER BY sort_order',[uuid(req.params.id)])).rows;}));
app.post('/manage/contests/:id/problems',run(async req=>{admin(req);const b=z.object({name:z.string().min(1),description:z.string().min(1),points:z.number().nonnegative()}).parse(req.body);return tx(async db=>{await db.query('SELECT id FROM contests WHERE id=$1 FOR UPDATE',[uuid(req.params.id)]);return(await db.query(`INSERT INTO contest_problems(creator_id,contest_id,name,description,points,sort_order) VALUES($1,$2,$3,$4,$5,(SELECT coalesce(max(sort_order),-1)+1 FROM contest_problems WHERE contest_id=$2)) RETURNING id`,[req.user.sub,req.params.id,b.name,b.description,b.points])).rows[0];});}));
app.get('/manage/contests/:id/submissions',run(async req=>{admin(req);return(await query('SELECT s.id,s.content,s.score,s.status,s.problem_id,u.name FROM contest_submissions s JOIN users u ON u.id=s.participant_id WHERE contest_id=$1 ORDER BY submitted_at DESC LIMIT 100',[uuid(req.params.id)])).rows;}));
app.patch('/manage/submissions/:id',run(async req=>{admin(req);const b=z.object({score:z.number().nonnegative(),status:z.enum(['accepted','rejected','disqualified','judging'])}).parse(req.body);await tx(async db=>{const sub=(await db.query('SELECT contest_id,participant_id FROM contest_submissions WHERE id=$1',[uuid(req.params.id)])).rows[0];if(!sub)throw new ApiError(404,'Submission not found');await db.query('SELECT 1 FROM contest_participants WHERE contest_id=$1 AND participant_id=$2 FOR UPDATE',[sub.contest_id,sub.participant_id]);await db.query('UPDATE contest_submissions SET score=$1,status=$2,judged_at=now(),judged_by=$3 WHERE id=$4',[b.score,b.status,req.user.sub,req.params.id]);await db.query(`UPDATE contest_participants SET points=(SELECT coalesce(sum(best),0) FROM(SELECT max(score) best FROM contest_submissions WHERE contest_id=$1 AND participant_id=$2 AND status='accepted' GROUP BY problem_id) scores) WHERE contest_id=$1 AND participant_id=$2`,[sub.contest_id,sub.participant_id]);});}));
listen(app,process.env.FRONTEND_API_PORT||4010,'frontend-api');
