import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{once}from'node:events';import{db,query,server}from'./harness.js';
test('frontend adapter: SQL and authorization integration',async t=>{
  let sql=await readFile(new URL('../../backend/database/001_initial_schema.sql',import.meta.url),'utf8');
  // Embedded PostgreSQL does not load Supabase extensions here. CITEXT is mapped
  // to TEXT for tests; case-insensitive uniqueness still needs a Supabase smoke test.
  sql=sql.replace(/CREATE EXTENSION IF NOT EXISTS (pgcrypto|citext);/g,'').replace(/\bCITEXT\b/g,'TEXT');
  await db.exec(sql);
  await db.exec(await readFile(new URL('../../backend/database/003_platform_settings.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../../backend/database/004_instructors.sql',import.meta.url),'utf8'));
  await db.exec(await readFile(new URL('../../backend/database/005_profile_course_media.sql',import.meta.url),'utf8'));
  let source=await readFile(new URL('../../backend/services/frontend/src/server.js',import.meta.url),'utf8');
  source=source.replace("import bcrypt from 'bcryptjs';","const bcrypt={hash:async value=>'test-only:'+value};")
    .replace("'@uddeepto/common'",JSON.stringify(new URL('./harness.js',import.meta.url).href))
    .replace("'express'",JSON.stringify(import.meta.resolve('express')))
    .replace("'zod'",JSON.stringify(import.meta.resolve('zod')));
  await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));await once(server,'listening');
  const base=`http://127.0.0.1:${server.address().port}`;
  const ids={};for(const[name,role]of[['Learner','learner'],['Other','learner'],['Hirer','hirer'],['Admin','admin']])ids[name]=(await query('INSERT INTO users(name,email,username,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id',[name,`${name}@example.com`,name,'test-only',role])).rows[0].id;
  const category=(await query("INSERT INTO interest_categories(name,slug,icon) VALUES('Web Development','web-development','code') RETURNING id")).rows[0].id;
  async function request(path,{as='Learner',method='GET',body,headers={}}={}){const r=await fetch(base+path,{method,headers:{'x-test-user':ids[as],'Content-Type':'application/json',...headers},body:body?JSON.stringify(body):undefined});const data=await r.json();return{status:r.status,data};}
  async function ok(path,opts){const r=await request(path,opts);assert.equal(r.status,200,JSON.stringify(r));return r.data;}
  let instructor;
  try{
    await t.test('dashboard and safe profile projection',async()=>{const d=await ok('/dashboard');assert.equal(Number(d.enrollments),0);const p=await ok('/profile/'+ids.Other);assert.equal(p.password_hash,undefined);assert.equal(p.email,undefined);});
    await t.test('hirer blocked from learning catalog, learner blocked from admin',async()=>{assert.equal((await request('/catalog/courses',{as:'Hirer'})).status,403);assert.equal((await request('/admin/users')).status,403);});
    instructor=null;
    await t.test('admin creates searchable instructor profiles with a photo and social links',async()=>{assert.equal((await request('/admin/instructors',{method:'POST',body:{name:'Nurul Alam Ador',details:'Frontend engineering and product design'}})).status,403);instructor=await ok('/admin/instructors',{as:'Admin',method:'POST',headers:{'x-test-upload':'image/png'},body:{name:'Nurul Alam Ador',designation:'Senior instructor',details:'Frontend engineering and product design',linkedin_url:'https://linkedin.com/in/nurul',remove_image:'false'}});assert.equal(instructor.name,'Nurul Alam Ador');assert.equal(instructor.designation,'Senior instructor');assert.equal(instructor.social_links.linkedin,'https://linkedin.com/in/nurul');assert.equal(instructor.has_image,true);const matches=await ok('/admin/instructors?q=Nurul',{as:'Admin'});assert.equal(matches.length,1);assert.equal(Number(matches[0].course_count),0);assert.equal(matches[0].image_blob,undefined);const image=await fetch(`${base}/instructors/${instructor.id}/image`,{headers:{'x-test-user':ids.Admin}});assert.equal(image.status,200);assert.match(image.headers.get('content-type'),/image\/png/);assert.ok((await image.arrayBuffer()).byteLength>0);});
    let course;
    await t.test('admin creates and publishes courses with an instructor and cover; public catalog filters draft',async()=>{assert.equal((await request('/admin/courses',{as:'Admin',method:'POST',body:{title:'Missing instructor',slug:'missing-instructor',description:'Must fail',category_id:category,price:0,status:'draft'}})).status,422);course=(await ok('/admin/courses',{as:'Admin',method:'POST',headers:{'x-test-upload':'image/webp'},body:{title:'Practical JS',slug:'practical-js',description:'Learn JavaScript',category_id:category,instructor_id:instructor.id,price:0,currency:'BDT',status:'published'}})).id;await ok('/admin/courses',{as:'Admin',method:'POST',body:{title:'Draft',slug:'draft',description:'Hidden',category_id:category,instructor_id:instructor.id,price:0,status:'draft'}});const list=await ok('/catalog/courses?tab=explore');assert.equal(list.length,1);assert.equal(list[0].id,course);assert.equal(list[0].instructor_id,instructor.id);assert.equal(list[0].instructor_name,'Nurul Alam Ador');assert.equal(list[0].instructor_details,'Frontend engineering and product design');assert.equal(list[0].instructor_designation,'Senior instructor');assert.equal(list[0].has_cover_image,true);const cover=await fetch(`${base}/course-covers/${course}`,{headers:{'x-test-user':ids.Learner}});assert.equal(cover.status,200);assert.match(cover.headers.get('content-type'),/image\/webp/);});
    await t.test('every account can update its profile picture and cover image',async()=>{await ok('/profile',{as:'Learner',method:'PATCH',headers:{'x-test-upload':'image/png','x-test-upload-field':'picture,cover_image'},body:{name:'Learner',username:'Learner',bio:'Updated profile',interest_ids:[],remove_picture:'false',remove_cover_image:'false'}});const profile=await ok(`/profile/${ids.Learner}`);assert.equal(profile.has_picture,true);assert.equal(profile.has_cover_image,true);const picture=await fetch(`${base}/profile/${ids.Learner}/picture`,{headers:{'x-test-user':ids.Learner}});assert.equal(picture.status,200);const cover=await fetch(`${base}/profile/${ids.Learner}/cover`,{headers:{'x-test-user':ids.Learner}});assert.equal(cover.status,200);});
    await t.test('admin control center, filtered tables, user creation and settings',async()=>{assert.equal((await request('/admin/overview')).status,403);const overview=await ok('/admin/overview',{as:'Admin'});assert.equal(Number(overview.stats.total_users),4);assert.equal(Number(overview.stats.courses),2);const drafts=await ok('/admin/courses?status=draft&q=Draft',{as:'Admin'});assert.equal(drafts.length,1);assert.equal(drafts[0].creator_name,'Admin');const users=await ok('/admin/users?q=Admin',{as:'Admin'});assert.equal(users.length,1);assert.equal(users[0].email,'Admin@example.com');assert.equal((await request(`/admin/users/${ids.Other}`,{as:'Admin',method:'PATCH',body:{role:'instructor'}})).status,422);assert.deepEqual(await ok('/admin/settings',{as:'Admin'}),{registration_open:true,content_review_required:true});await ok('/admin/settings',{as:'Admin',method:'PATCH',body:{registration_open:false,content_review_required:false}});assert.deepEqual(await ok('/admin/settings',{as:'Admin'}),{registration_open:false,content_review_required:false});const created=await ok('/admin/users',{as:'Admin',method:'POST',body:{name:'New Hirer',email:'new-hirer@example.com',username:'new_hirer',password:'secure-password',role:'hirer'}});assert.equal(created.role,'hirer');assert.equal((await query('SELECT password_hash FROM users WHERE id=$1',[created.id])).rows[0].password_hash,'test-only:secure-password');});
    await t.test('paid course text never appears in material metadata; completion requires enrollment',async()=>{const m=await ok(`/manage/courses/${course}/materials`,{as:'Admin',method:'POST',body:{name:'First lesson',content_text:'Protected lesson',is_preview:false}});const d=await ok(`/detail/courses/${course}`);assert.equal(d.materials[0].content_text,undefined);assert.equal((await request(`/courses/${course}/complete/${m.id}`,{method:'PUT'})).status,403);await query('INSERT INTO course_enrollments(course_id,user_id) VALUES($1,$2)',[course,ids.Learner]);await ok(`/courses/${course}/complete/${m.id}`,{method:'PUT'});assert.equal((await query('SELECT status FROM course_enrollments WHERE course_id=$1',[course])).rows[0].status,'completed');});
    let post;
    await t.test('showcase reactions, comments, and admin report queue',async()=>{post=(await query("INSERT INTO showcase_posts(creator_id,category_id,content) VALUES($1,$2,'My project') RETURNING id",[ids.Learner,category])).rows[0].id;await ok(`/showcase/${post}/reaction`,{method:'PUT'});assert.equal(Number((await ok('/showcase'))[0].reactions),1);await ok(`/showcase/${post}/reaction`,{method:'PUT'});assert.equal(Number((await ok('/showcase'))[0].reactions),0);const c=await ok(`/showcase/${post}/comments`,{as:'Other',method:'POST',body:{content:'Great progress'}});await ok(`/comments/${c.id}/reaction`,{method:'PUT'});assert.equal(Number((await ok(`/showcase/${post}/comments`))[0].reactions),1);const report=(await query("INSERT INTO reported_showcase_posts(post_id,reporter_id,reason,details) VALUES($1,$2,'spam','Copied material') RETURNING id",[post,ids.Other])).rows[0].id;const reports=await ok('/admin/reported_showcase_posts?status=pending&q=spam',{as:'Admin'});assert.equal(reports.length,1);assert.equal(reports[0].post_content,'My project');const overview=await ok('/admin/overview',{as:'Admin'});assert.equal(Number(overview.stats.open_reports),1);assert.ok(overview.activity.some(item=>item.kind==='report'));await ok(`/admin/reported_showcase_posts/${report}`,{as:'Admin',method:'PATCH',body:{status:'reviewing',resolution_note:'Assigned for review'}});const reviewed=(await query('SELECT status,reviewed_by FROM reported_showcase_posts WHERE id=$1',[report])).rows[0];assert.equal(reviewed.status,'reviewing');assert.equal(reviewed.reviewed_by,ids.Admin);});
    await t.test('private posts and cross-user deletes rejected',async()=>{assert.equal((await request(`/showcase/${post}`,{as:'Other',method:'DELETE'})).status,403);await query("UPDATE showcase_posts SET visibility='private' WHERE id=$1",[post]);assert.equal((await request(`/showcase/${post}/comments`)).status,404);});
    await t.test('community creation includes owner and channel; outsiders cannot read chat',async()=>{const c=await ok('/communities',{method:'POST',body:{name:'Creative coders',slug:'creative-coders',description:'A community',category_id:category,requires_approval:true,is_private:true}});const detail=await ok(`/communities/${c.id}`);assert.equal(detail.membership,'approved');const chat=detail.chats[0].id;await ok(`/communities/${c.id}/chats/${chat}`,{method:'POST',body:{content:'Welcome!'}});assert.equal((await request(`/communities/${c.id}/chats/${chat}`,{as:'Other'})).status,403);const list=await ok('/catalog/communities');assert.equal(list.length,1);});
    await t.test('one-to-one conversation deduplicates and rejects nonmembers',async()=>{const c=await ok('/messages',{method:'POST',body:{user_id:ids.Other}});const again=await ok('/messages',{method:'POST',body:{user_id:ids.Other}});assert.equal(c.id,again.id);await ok(`/messages/${c.id}`,{method:'POST',body:{content:'Hello!'}});assert.equal((await ok(`/messages/${c.id}`,{as:'Other'}))[0].content,'Hello!');assert.equal((await request(`/messages/${c.id}`,{as:'Admin'})).status,404);});
    await t.test('job applications are visible only to owner/admin',async()=>{const job=(await query("INSERT INTO jobs(creator_id,title,description,type,status) VALUES($1,'Developer','Build things','permanent','open') RETURNING id",[ids.Hirer])).rows[0].id;await query('INSERT INTO job_applications(job_id,applicant_id,cover_letter) VALUES($1,$2,$3)',[job,ids.Learner,'Interested']);assert.equal((await request(`/jobs/${job}/applications`)).status,403);assert.equal((await ok(`/jobs/${job}/applications`,{as:'Hirer'})).length,1);await ok(`/jobs/${job}/applications/${ids.Learner}`,{as:'Hirer',method:'PATCH',body:{status:'shortlisted'}});assert.equal((await ok('/jobs?tab=applied'))[0].application_status,'shortlisted');});
    await t.test('webinar capacity enforced and meeting URL private before registration',async()=>{const w=(await query("INSERT INTO webinars(creator_id,name,description,category_id,status,starting_time,ending_time,capacity,meeting_url) VALUES($1,'Live session','Learn together',$2,'scheduled',now()+interval '1 day',now()+interval '2 days',1,'https://example.com/meeting') RETURNING id",[ids.Admin,category])).rows[0].id;assert.equal((await ok(`/detail/webinars/${w}`)).meeting_url,null);await ok(`/webinars/${w}/join`,{method:'POST'});assert.equal((await ok(`/detail/webinars/${w}`)).meeting_url,'https://example.com/meeting');assert.equal((await request(`/webinars/${w}/join`,{as:'Other',method:'POST'})).status,409);assert.equal((await ok('/catalog/webinars?tab=upcoming')).length,1);});
    await t.test('contest entry, submission, admin judging and leaderboard',async()=>{const c=(await query("INSERT INTO contests(creator_id,name,description,category_id,status,starting_time,ending_time) VALUES($1,'Challenge','Try your skills',$2,'published',now()-interval '1 hour',now()+interval '1 hour') RETURNING id",[ids.Admin,category])).rows[0].id;const p=await ok(`/manage/contests/${c}/problems`,{as:'Admin',method:'POST',body:{name:'First problem',description:'Explain your approach',points:100}});await ok(`/contests/${c}/join`,{method:'POST'});const s=await ok(`/contests/${c}/submit`,{method:'POST',body:{problem_id:p.id,content:'My solution'}});await ok(`/manage/submissions/${s.id}`,{as:'Admin',method:'PATCH',body:{score:75,status:'accepted'}});assert.equal(Number((await ok(`/detail/contests/${c}`)).leaderboard[0].points),75);assert.equal((await ok('/catalog/contests?tab=ongoing')).length,1);});
    await t.test('deleting an instructor removes only the profile and unassigns courses',async()=>{const removed=await ok(`/admin/instructors/${instructor.id}`,{as:'Admin',method:'DELETE'});assert.equal(removed.unassigned_courses,2);const assigned=await query('SELECT instructor_id FROM courses WHERE id=$1',[course]);assert.equal(assigned.rows[0].instructor_id,null);});
    await t.test('admin cannot disable own account; suspended user is denied',async()=>{assert.equal((await request('/admin/users/'+ids.Admin,{as:'Admin',method:'PATCH',body:{account_status:'suspended'}})).status,409);await query("UPDATE users SET account_status='suspended' WHERE id=$1",[ids.Other]);assert.equal((await request('/dashboard',{as:'Other'})).status,401);});
  }finally{await new Promise(resolve=>server.close(resolve));await db.close();}
});
