export const adminFields = {
  users: {
    name: "text",
    email: "email",
    username: "text",
    role: ["learner", "hirer", "admin"],
    account_status: ["active", "suspended", "deactivated"],
  },
  interest_categories: {
    name: "text",
    slug: "text",
    icon: "text",
    description: "textarea",
    is_active: "boolean",
  },
  courses: {
    title: "text",
    slug: "text",
    description: "textarea",
    cover_image: "image",
    category_id: "category",
    instructor_id: "instructor",
    price: "number",
    currency: "text",
    status: ["draft", "published", "archived"],
  },
  contests: {
    name: "text",
    description: "textarea",
    category_id: "category",
    type: ["general", "competitive_programming", "drawing", "singing"],
    entry_fee: "number",
    currency: "text",
    status: ["draft", "published", "cancelled", "completed"],
    max_participants: "number",
    starting_time: "datetime-local",
    ending_time: "datetime-local",
  },
  webinars: {
    name: "text",
    description: "textarea",
    category_id: "category",
    meeting_url: "url",
    capacity: "number",
    status: ["draft", "scheduled", "live", "completed", "cancelled"],
    starting_time: "datetime-local",
    ending_time: "datetime-local",
  },
  jobs: {
    title: "text",
    description: "textarea",
    category_id: "category",
    type: ["permanent", "contract", "internship", "part_time", "freelance", "one_time"],
    status: ["draft", "open", "closed", "filled", "cancelled"],
    location: "text",
    criteria: "textarea",
    salary_min: "number",
    salary_max: "number",
    currency: "text",
    salary_period: ["fixed", "hourly", "daily", "weekly", "monthly", "yearly"],
    application_deadline: "datetime-local",
    is_remote: "boolean",
  },
  communities: {
    name: "text",
    slug: "text",
    description: "textarea",
    category_id: "category",
    requires_approval: "boolean",
    is_private: "boolean",
  },
};
